mizzy/specinfra

- lib/specinfra/command/base/host.rb
I don't believe nslookup on it's own will give you the expected exit code on the latest Ubuntu 12.04. Dig behaves similarly in Ubuntu 12.04.   I have confirmed that nslookup will return 0 whether or not nslookup finds a record.  Exit codes for nslookup are fixed in Ubuntu 14.04.  
This pull request is a  proposed workaround for Ubuntu 12.04 that uses nslookup in a pipe.  
nslookup -timeout=1 google.com
Server:          10.0.2.3
Address:     10.0.2.3#53
Non-authoritative answer:
Name:     google.com
Address: 74.125.239.134
Name:     google.com
Address: 74.125.239.132
Name:     google.com
Address: 74.125.239.133
Name:     google.com
Address: 74.125.239.137
Name:     google.com
Address: 74.125.239.135
Name:     google.com
Address: 74.125.239.142
Name:     google.com
Address: 74.125.239.136 …
> nslookup exit code workaround

- lib/specinfra/command/base/routing_table.rb
- lib/specinfra/processor.rb
ECMP means that a route can have multiple destinations, E.g.
$ ip route show 10.2.1.4
10.2.1.4  proto zebra  metric 20
nexthop via 10.2.1.1  dev swp49 weight 1 onlink
nexthop via 10.2.1.1  dev swp50 weight 1 onlink
nexthop via 10.2.1.2  dev swp51 weight 1 onlink
nexthop via 10.2.1.2  dev swp52 weight 1 onlink
This patch modifies the routing_table resource to support the different output for multiple destination routes:
$ ip route show
default via 192.168.0.1 dev eth0
10.2.1.2  proto zebra  metric 20
nexthop via 10.2.1.2  dev swp1 weight 1 onlink
nexthop via 10.2.1.2  dev swp2 weight 1 onlink
nexthop via 10.2.1.2  dev swp3 weight 1 onlink
nexthop via 10.2.1.2  dev swp4 weight 1 onlink
10.4.1.0/25 dev br0  proto kernel  scope link  src 10.4.1.1
10.4.1.128/25 dev br1  proto kernel  scope …
> Support routes with multiple destinations

- lib/specinfra/configuration.rb
When using sprockets and specinfra together, our project would occasionally run into problems when compiling assets due to specinfra attempting to create an instance variable with an invalid name. While I'm not entirely sure *why* this behavior would occur, it was more straightforward to patch specinfra than go down the rabbit holes to determine what was causing the two libraries to occasionally not play nicely together.
This change simply wraps the calls to ```#set_instance_variable``` and ```#get_instance_variable``` in a begin/rescue block. Please let me know if you would prefer to have this fixed in a different way, and I'll be happy to update.
Thanks!
> Handle NameError exception if an invalid variable name reaches method_missing

- lib/specinfra/command/opensuse/base/service.rb
This PR adds all systemd functions to opensuse and overrides the is_enabled check to ensure
we also check for sysv style files in case we don't have a systemd service
```
$ /bin/systemctl is-enabled logstash.service
logstash.service is not a native service, redirecting to /sbin/chkconfig.
Executing /sbin/chkconfig logstash --level=5
enabled
$ /bin/systemctl is-enabled elasticsearch.service
enabled
```
> Include other systemd actions and override is_enabled check

- lib/specinfra/command/base/service.rb
Adds support for `should be_running.under('runit')`.  Similar to `daemontools`, except it automatically uses `/etc/service` and the output is easier to test.
> Add check_is_running_under_runit.

- lib/specinfra/command/freebsd/base/service.rb
FreeBSD's default value of svscan service directory is `/var/service`.
See also:
http://sources.freebsd.org/HEAD/ports/sysutils/daemontools/files/svscan.in
> svscan_servicedir	The directory containing the various service.
>			directories to be monitored.  Professor Daniel J.
>			Bernstein recommends "/service", but the FreeBSD
>			port has a default of "/var/service" instead
> Support daemontools with FreeBSD

- lib/specinfra/command/darwin/base/file.rb
This PR removes `-f` option from `get_link_target` on darwin.
Because darwin(OSX)'s readlink differs from GNU readlink, `-f`option is unavailable.
```sh
$ readlink -f wercker.yml
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```
> remove `-f` option from darwin get_link_target

- lib/specinfra/backend/docker.rb
In the Docker API v1.15 logs=true is required to capture
stdout and stderr logs
stdout - if logs=true, return stdout log, if stream=true,
attach to stdout. Default false
https://docs.docker.com/reference/api/docker_remote_api_v1.15/
> Set logs = true when attaching to Docker backend

- lib/specinfra/command/base/cron.rb
cronの確認コマンドに2点問題がありそうなので修正しました。
1つは`#`を含むエントリがコメントとみなされて
```
* * * * * command '### abc ###'
```
以下のテストがエラーになることです。
```ruby
it { should have_entry("* * * * * command '### abc ###").with_user('mikeda') }
```
もう1つはgrepに^、$が無いためこういうエントリに対して
```
10 * * * * command1 | command2
```
以下のテストが通ってしまうことです。
```ruby
describe cron do
it { should have_entry("10 * * * * command1").with_user('mikeda') }
it { should have_entry("0 * * * * command1 | command2").with_user('mikeda') }
end
```
2つめに関してはコマンド部分のみを確認していたユーザなど、既存テストに影響をあたえる可能性が有ります。
```ruby
describe cron do
it { should have_entry("command1").with_user('mikeda') }
end
```
> Fix regex for crontab

- lib/specinfra/command/base/group.rb
- spec/command/base/group_spec.rb
Add 3 commands to base group:
- `add_group` - Create new group
- `get_group_gid` - Get gid from group's name
- `update_group_gid` - Update group's gid
> Add commands to base group

- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/platform.rb
- lib/specinfra/host_inventory/platform_version.rb
You can get `host_inventory['platform']` and `host_inventory['platform_version']` with this fix.
`host_inventory['platform']` is not compatible with Ohai, for example, it returns `redhat` with CentOS or other Red Hat based Linux.
> Support host_inventory['platform'] and host_inventory['platform_version']

- lib/specinfra/host_inventory/memory.rb
You can get memory information like Ohai with this fix.
```ruby
[6] pry(main)> host_inventory['memory']
=> {"swap"=>{"cached"=>"0kB", "total"=>"950264kB", "free"=>"950264kB"},
"total"=>"469452kB",
"free"=>"86860kB",
"buffers"=>"23232kB",
"cached"=>"257908kB",
"active"=>"91472kB",
"inactive"=>"201376kB",
"dirty"=>"36kB",
"writeback"=>"0kB",
"anon_pages"=>"11756kB",
"mapped"=>"6928kB",
"slab"=>"78664kB",
"slab_reclaimable"=>"28940kB",
"slab_unreclaim"=>"49724kB",
"page_tables"=>"2420kB",
"nfs_unstable"=>"0kB",
"bounce"=>"0kB",
"commit_limit"=>"1184988kB",
"committed_as"=>"72152kB",
"vmalloc_total"=>"34359738367kB",
"vmalloc_used"=>"16384kB",
"vmalloc_chunk"=>"34359712252kB"}
```
> Support host_inventory['memory']

- lib/specinfra/command/linux/base/inventory.rb
- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/filesystem.rb
You can get filesystem information like this.
```ruby
[3] pry(main)> host_inventory['filesystem']
=> {"/dev/mapper/VolGroup-lv_root"=>
{"kb_size"=>"39841176",
"kb_used"=>"1565824",
"kb_available"=>"36251520",
"percent_used"=>"5%",
"mount"=>"/"},
"tmpfs"=>
{"kb_size"=>"234724",
"kb_used"=>"0",
"kb_available"=>"234724",
"percent_used"=>"0%",
"mount"=>"/dev/shm"},
"/dev/sda1"=>
{"kb_size"=>"495844",
"kb_used"=>"31887",
"kb_available"=>"438357",
"percent_used"=>"7%",
"mount"=>"/boot"},
"vagrant"=>
{"kb_size"=>"244277768",
"kb_used"=>"205117140",
"kb_available"=>"39160628",
"percent_used"=>"84%",
"mount"=>"/vagrant"}}
```
Support only Linux currently.
> Support getting filesystem information

- lib/specinfra/command/debian/base/service.rb
We amended an upstart script to not start by changing it to "start on []" instead of removing the "start on" line, added a serverspec test to expect(service 'foo').to_not be_enabled, but the test failed because it matched "start on" in the upstart script. 
I then added "expect(service 'foo').to_not be_enabled.with_level(2)" as a workaround, but noticed that didn't seem to work either.
This change request attempts to match a specific runlevel in the upstart script on the "start on" line.
To the best of my brief readings about upstart and observations with our upstart script amendment, "start on []" does not enable that service for any runlevel. I could be very wrong about this.
> Check runlevel in upstart service enabled

- lib/specinfra/command/base/mail_alias.rb
this pr makes serverspec correctly identify alias targets that are enclosed in either single or double quotes.
The chef community cookbook for postfix set aliases this way, for example.
> allow quotes around mail_alias targets

- lib/specinfra/command/windows/base/file.rb
This fundamentally broke after changing from version 1 in our implementation.  This is more exact than the previous as it will require the 'Group\User'
> Add the check_is_owned_by method back into windows

- lib/specinfra/command/windows/base/file.rb
Also found that with 2003 and 2008 it was not exiting properly unless PowerShell v3+ was installed.  This improved way works with Powershell v2
> Fix issue when duplicate owners are present on file as is possible in windows

- lib/specinfra/command/linux/base/interface.rb
works on any physical port by getting speed value from /sys/class/net
value is in MB.
port must be activated i.e `ip link set <dev> up` before variable shows up.
confirmed to work on ubuntu/debian/centos/cumulus linux
> easier way of obtaining speed in linux 

- lib/specinfra/command/base/package.rb
- spec/command/base/package_spec.rb
This pull request lets you check if a ruby is installed by RVM, e.g. ruby 2.2.0, rbx 2.4.1, jruby 1.6.8, etc.
It can be used in serverspec like this:
```
describe package('ruby') do
it { should be_installed.by('rvm').with_version('2.2.0') }
end
describe package('ruby') do
it { should_not be_installed.by('rvm').with_version('1.8.7') }
end
```
I am also opening a pull request for the serverspec/serverspec repo, adding some tests there.
> Add check for if a ruby is installed by RVM

- lib/specinfra/command/windows/base/file.rb
- don't break over the line
- use $() to fix
"The term 'if' is not recognized as the name of a cmdlet, function,
script file,"
reference:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/d7cd6096-00c5-46d9-882d-29ae38ade748/why-does-if1-eq-1yes-failed-with-the-term-if-is-not-recognized-as-the-name-of-a?forum=winserverpowershell
> fix check_is_owned_by method for windows

- lib/specinfra/command/redhat/base/package.rb
<pre>
describe package('foo') do
be_installed_by("rpm").with_version("1.1")
end
</pre>
This code should match foo-1.1 or foo-1.1.x, etc... 
But current code match foo-0.1.1 , foo-2.1.1.
Please fixed it.
> Fixed rpm's version check allows partial matching.

- lib/specinfra/command/base/user.rb
- spec/command/base/user_spec.rb
If `useradd` doesn't have `-m` option, `useradd` will not create home directory on Debian-based Linux and will create on RHEL-based Linux.
Because `CREATE_HOME` of `/etc/login.def` on RHEL-based Linux is set to yes as default.
So, `useradd` should have `:create_home` to add `-m`.
Do you think about?
> Add `-m` to `useradd` options

- Rakefile
- lib/specinfra/command/linux/base/inventory.rb
- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/cpu.rb
- spec/command/linux/inventory_spec.rb
- spec/host_inventory/cpu_spec.rb
- spec/spec_helper.rb
Add cpu information to `host_inventory` (like Ohai)
Example:
```shell
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3132.076
cache size	: 6144 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl pni ssse3 lahf_lm
bogomips	: 6264.15
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model …
```
> Support host_inventory['cpu']

- lib/specinfra/backend/docker.rb
create_and_start_container is failing for docker images without CMD or ENTRYPOINT (base images for example)
/bin/sh is present almost in any image, except scratch, so i suggest to use it's internal command "read" to start container and wait if cmd is nil for image
> Set Cmd for container in create_and_start_container if image has none

- lib/specinfra/command/debian/base/service.rb
This reverts commit d73a82c2519095b1ae9aa04eaeb205308897cf3c from #309. As pointed out in the issue and comments, many upstart services don't even supply a runlevel or control startup based on some other parameter than runlevel, e.g.:
`start on virtual-filesystems` (/etc/init/udev.conf)
`start on started networking` (/etc/init/rabbitmq-server.conf)
Perhaps a separate `.with_runlevel` could be added instead, but the default check for a service enabled on ubuntu should not look for a runlevel.
> runlevel check in upstart is broken

- lib/specinfra/backend/docker.rb
JSON payload returned from docker-api has the 'Cmd' attribute nested under 'Config'. [Here](https://github.com/serverspec/serverspec/blob/63738916c4a49edb05e3bfd4572d2d96f10ff718/spec/type/linux/docker_container_spec.rb#L23) is an example.
Fixed incorrect usage of `read` for `/bin/sh`. Instead, just open up `/bin/sh` with no command.
> Fix #325. Cmd lives under Config

- lib/specinfra/host_inventory.rb
Change Host Inventory to enumerable object (like Hash)
We can get all available keys and values by this feature.
Examlple:
```shell
[1] pry(main)> require 'specinfra'
=> true
[2] pry(main)> host_inventory.keys
=> ["memory", "ec2", "hostname", "domain", "fqdn", "platform", "platform_version", "filesystem", "cpu"]
[3] pry(main)> host_inventory.each{|k,v| p k,v}
"memory"
{"swap"=>{"cached"=>"0kB", "total"=>"2097148kB", "free"=>"2097148kB"}, "total"=>"4048272kB", "free"=>"1668476kB", "buffers"=>"300800kB", "cached"=>"744132kB", "active"=>"1390440kB", "inactive"=>"729700kB", "dirty"=>"0kB", "writeback"=>"0kB", "anon_pages"=>"1075204kB", "mapped"=>"238712kB", "slab"=>"189608kB", "slab_reclaimable"=>"169036kB", "slab_unreclaim"=>"20572kB", "page_tables"=>"25700kB", "nfs_unstable"=>"0kB", …
```
> Change Host Inventory to enumerable

- lib/specinfra/command.rb
- lib/specinfra/command/alpine.rb
- lib/specinfra/command/alpine/base.rb
- lib/specinfra/command/alpine/base/package.rb
- lib/specinfra/command/alpine/base/process.rb
- lib/specinfra/helper/detect_os.rb
- lib/specinfra/helper/detect_os/alpine.rb
This adds support for [Alpine Linux](https://www.alpinelinux.org). A Linux distribution that is gaining traction in the Docker community due to [the lightweight of the base image](http://gliderlabs.viewdocs.io/docker-alpine).
> Add Alpine Linux support

- lib/specinfra/backend/docker.rb
- lib/specinfra/configuration.rb
Example:
```ruby
RSpec.configure do |config|
config.docker_container_create_options = {
'Cmd' => ['/usr/bin/tail', '-f', '/dev/null'] # keep-alive
}
end
```
For all options, see: https://docs.docker.com/reference/api/docker_remote_api_v1.17/#create-a-container
In the above example, we are testing a "base image" that has no long running process, but we still want to test that the image was built according to the spec.
> Docker: add docker_container_create_options option

- lib/specinfra/command/arch/base/package.rb
- lib/specinfra/command/debian/base/package.rb
- lib/specinfra/command/redhat/base/package.rb
I added remove_package method to implement `:remove` action to [itamae](https://github.com/itamae-kitchen/itamae) .
Here's my branch: https://github.com/itamae-kitchen/itamae/compare/master...eagletmt:remove-package
This PR adds support for pacman, apt and yum.
I've tested only pacman version for now (not tested apt and yum yet).
> Add remove_package method to some Linux environments

- lib/specinfra/command.rb
- lib/specinfra/command/smartos/base/file.rb
- lib/specinfra/command/smartos/base/package.rb
- lib/specinfra/command/smartos/base/service.rb
These changes fix a few issues:
- On SmartOS, the tools for checking md5 and sha256 hashes will not always be available. Instead, use the digest command.
- On SmartOS, GNU grep will not always be installed so commands like the following will fail because the '-x' flag will not be recognized:
```
cmd = "/opt/local/bin/pkgin list 2> /dev/null | grep -qw ^#{escape(package)}"
```
- Instead, use the pkg_info command to check if a package is installed (and use awk to pull out the package version)
- Similarly, the service checks will also fail if GNU grep is not available. Instead, don't rely on the '-x' flag (and use the `svcs -Ho state` command instead)
> Improvements for smartos

- lib/specinfra/backend/exec.rb
I was getting this error while running my tests:
```
NoMethodError:
undefined method `shellescape' for #<Specinfra::Backend::PowerShell::Command:0x00000106831240>
```
This PR fixes that.
> Convert cmd to string before calling shellescape

- lib/specinfra/command/base/host.rb
Right now code like `expect(host('somehost')).to be_resolvable.by('hosts')` may return a false positive when finds a name in a comment line.
According to `man 5 hosts`
> Text from a "#" character until the end of the line is a comment, and is ignored.
so we should cut comments before looking up host name.
> Ignore comments in /etc/hosts

- lib/specinfra/ec2_metadata.rb
> undefined method `to_camel_case' for :XXX:Symbol (NoMethodError)
> Avoid error on symbols

- lib/specinfra/backend/docker.rb
Default value of Specinfra.configuration.env is nil. So if env is nil, ```Specinfra.configuration.env.any?``` got NoMethodError.
And NilClass has to_a method. so not need to check it via any? method.
> not need to check Specinfra.configuration.env via any? in  backend/docker.rb

- lib/specinfra/command/module/zfs.rb
To implement 'its(:property)' in Serverspec::Type::Zfs,
add get_property in Specinfra::Command::Module::Zfs.
> add get_property in Specinfra::Command::Module::Zfs

- lib/specinfra/command/solaris/base/service.rb
To implement 'its(:property)' syntax to test property of Solaris service,
add get_property in Specinfra::Command::Solaris::Base::Service.
> add get_property in Specinfra::Command::Solaris::Base::Service

- lib/specinfra/backend/docker.rb
After this [commit](https://github.com/serverspec/specinfra/commit/8f80161879f0843cf5f0aa7e46b8c77a637f7d0e), Base class set ```@config``` in initialize process. 
Docker backend also has self initialize process and call  ```get_config``` method. So currently this method got ```undefined method `[]' for nil:NilClass (NoMethodError)``` error. Because ```@config``` is nil. So need to call ```super``` method.
> call super at docker backend initialize

- lib/specinfra.rb
If this is true and backend is nil, an error will be raised.
> Add error_on_missing_backend_type option.

- lib/specinfra/command/linux/base/file.rb
- spec/command/linux/file_spec.rb
add method and test case to retrieve the selinux security context/label from a file by stat, for i.e.
```
describe file('/usr/bin/docker') do
its(:selinux_label) { should match /docker_exec_t/ }
end
```
> Integrate selinux file label

- lib/specinfra.rb
- lib/specinfra/backend/base.rb
- lib/specinfra/backend/docker.rb
- lib/specinfra/backend/dockerfile.rb
- lib/specinfra/backend/exec.rb
- lib/specinfra/backend/lxc.rb
- lib/specinfra/backend/shell_script.rb
- lib/specinfra/backend/ssh.rb
- lib/specinfra/backend/telnet.rb
- lib/specinfra/backend/winrm.rb
- lib/specinfra/command.rb
- lib/specinfra/command/module.rb
- lib/specinfra/command/module/systemd.rb
- lib/specinfra/command/module/zfs.rb
- lib/specinfra/core.rb
- lib/specinfra/ext.rb
- lib/specinfra/ext/class.rb
- lib/specinfra/ext/string.rb
- lib/specinfra/helper/detect_os.rb
- lib/specinfra/helper/os.rb
- lib/specinfra/helper/set.rb
In order to avoid helper methods are defined, split core classes into specinfra/core.rb. ([This commit](https://github.com/serverspec/specinfra/commit/ca985a7469dc8eb836c66485d7e0d1349634d422))
Related to the above change, I changed `module M1::M2` to `module M1; module M2`. Because specinfra/core does not [`include Specinfra`](https://github.com/serverspec/specinfra/blob/6f7247c1d2402986a0be19e48069c059b692c2f2/lib/specinfra.rb#L3), NameError will be occured.
(I know this change makes blame-ability less...)
This PR keeps compatiblity from older version.
> Introduce specinfra/core

- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/virtualization.rb
You can get virtualization infomationlike this.
```ruby
node[:virtualization]
```
Currently supports only docker for `node[:virtualization][:system]` .
> Add virtualization to host inventory

- lib/specinfra/command/openbsd/base/service.rb
The current code uses `rcctl`, which is a utility that is included in
OpenBSD 5.7, which is not yet released.
> Use OpenBSD rc.d scripts for service checks.

- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/arch.rb
- lib/specinfra/host_inventory/kernel.rb
Add OS architecture information to `host_inventory` (is the same as `os[:arch]`).
You can get architecture infomation like this.
```
node[:arch]
```
> Add arch to host inventory.

- lib/specinfra/command/redhat/base/yumrepo.rb
This PR is support CentOS 7 and Amazon Linux >= 2014.03(yum repolist).
Example:
```
$ yum repolist enabled -C
Loaded plugins: fastestmirror, priorities, update-motd, upgrade-helper
62 packages excluded due to repository priority protections
repo id                                                          repo name                                                                             status
!amzn-main/2014.09                                               amzn-main-Base                                                                         5019
!amzn-updates/2014.09                                            amzn-updates-Base                                                                      1178
...
```
Please see document http://man7.org/linux/man-pages/man8/yum.8.html:
>In …
> Support non-verbose mode(*) and old metadata(!)

- lib/specinfra/command/windows/base/file.rb
Get-Content can read files that are in use by another process, such as log files, where ReadAllText can not.
Example output from powershell for the differences:
````
PS C:\Users\vagrant> [System.IO.File]::ReadAllText("C:\Windows\Temp\test.log")
Exception calling "ReadAllText" with "1" argument(s): "The process cannot access the file 'C:\Window
cause it is being used by another process."
At line:1 char:30
+ [System.IO.File]::ReadAllText <<<< ("C:\Windows\Temp\test.log")
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : DotNetMethodException
PS C:\Users\vagrant> (Get-Content("C:\windows\Temp\test.log") | Out-String)
2015-04-14 03:32:07 nil INFO -> -> MARK <- <-
2015-04-14 03:33:16 nil INFO -> -> MARK <- <-
2015-04-14 03:34:16 nil INFO -> -> …
```
> Use `Get-Content` instead of `ReadAllText` to read file contents on Win

- lib/specinfra.rb
It seems that a product manager of Chef dislikes Specinfra, so I'll block requiring by Chef.
Ref: https://twitter.com/julian_dunn/status/588924310296915968
> Good bye Chef

- lib/specinfra/command.rb
- lib/specinfra/command/openbsd/base/bond.rb
While OpenBSD doesn't have a 'bond' driver, the equivalent is 'trunk'
which can also combine multiple interfaces into a single logical interface.
> Implement 'bond' type for OpenBSD

- .gitignore
When using tools like rvm, rbenv and others, it is useful to have
projects auto-setup based on the requirements of the project (selecting
a specific Ruby version, using a particular set of gems).
This helps keep the local developemnt environment from reporting "git
dirty" status.
> ignore local ruby version manager files

- lib/specinfra/command/debian/base/service.rb
In the event that multiple entries of a similarly-named service exist,
the pattern matching will incorrectly report that the described service is
enabled, when it is disabled.
In this example, two services exist, `nginx` and `nginx-example`.
With the current regular expression passed to grep, `is_enabled`
incorrectly returns that nginx is enabled.
expected Service "nginx" not to be enabled
/bin/sh -c ls\ /etc/rc3.d/\ \|\ grep\ --\ \'\^S..nginx\'\ \|\|\ grep\ \'start\ on\'\ /etc/init/nginx.conf
S20nginx-example
As can be seen on disk, the `nginx` service is prepended with `K` as it
is disabled, but the grep will respond with a different service.
root@fcf39505054b:~# ls /etc/rc3.d/
K80nginx  README  S20nginx-example  S99rc.local
root@fcf39505054b:~# ls /etc/rc3.d/ | grep -- '^S..nginx' ; …
> update debian service check for multiple matches

- lib/specinfra/command/base/package.rb
I would like to see the check_is_installed_by_pear method search for all pear packages across channels.  For example, the PHP redis library, Predis, comes from the pear.nrk.io channel, which doesn't show up in a `pear list` command.  `pear list -a` is needed to show Predis is installed.
`pear list` only shows installed packages in the default channel.
`pear list -a` shows all installed packages in all channels.
Found a reference online here: http://www.funkydata.net/2008/06/pear-list-installed-packages.html
And here is the difference between the two:
**pear list**
```
vagrant@vagrant-ubuntu-trusty-64:~$ pear list
Installed packages, channel pear.php.net:
=========================================
Package          Version State
Archive_Tar      1.3.11  stable
Console_Getopt   1.3.1   stable …
```
> Expand check_is_installed_by_pear to check all channels, not just default channel.

- lib/specinfra/backend/powershell/support/find_installed_application.ps1
Some Windows applications only install for the current user, so the registry keys end up under HKEY_CURRENT_USER and the package test fails. This change checks if the Uninstall paths also exist under `HKCU:\` and, if they do, searches there too.
This works in my testing, though I'm new to PowerShell. Hopefully it's not too ugly. :smile:
> Check HKEY_CURRENT_USER in addition to HKEY_LOCAL_MACHINE

- lib/specinfra/command/module/systemd.rb
Now only checks for a dot in service name, which causes an error with service names like "postgresql-9.3"
It should check explicitly for ".service" suffix (better, all known units suffixes, to avoid conflicts with .socket and similar)
> Check service name for systemd module

- lib/specinfra/command/linux/base/interface.rb
- spec/command/linux/interface_spec.rb
Add the get_link_state method for Linux interfaces to support the be_up? matcher.
> Interface state

- lib/specinfra/command.rb
- lib/specinfra/command/darwin/base/user.rb
- spec/command/darwin/user_spec.rb
This change adds the following 3 methods for darwin:
- check_has_home_directory
- check_has_login_shell
- get_home_directory
Because there is no `getent` command on darwin, we use [finger](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/finger.1.html) command instead. Here is an example output of `finger` command in my environment (Mac OS X 10.9.5)
```
$ finger r7kamura
Login: r7kamura       			Name: r7kamura
Directory: /Users/r7kamura          	Shell: /bin/zsh
On since 土  5  2 15:06 (JST) on console, idle 9 days 8:46 (messages off)
On since 土  5  2 15:06 (JST) on tty?? (messages off)
On since 月  5 11 16:00 (JST) on ttys000, idle 4:15
On since 木  5  7 06:55 (JST) on ttys001, idle 6:06
On since 木  5  7 06:45 (JST) on ttys002, idle 3 days 5:35
On since 木 …
```
> Support commands for home dir & login shell on darwin

- lib/specinfra/command/base/file.rb
- spec/command/base/file_spec.rb
When doing negative testing, I.e., asserting that 'this' path should not exist, it would be more concise to be able to express this in serverspec as:
```
describe File('/does_not_exist') do
it { should_not exist }
end
```
This PR adds necessary plumbing to specinfra to be able to implement this functionality in serverspec.
> add check_file_exists

- lib/specinfra/command/darwin/base/package.rb
`should be_installed.by('homebrew')` is already including in specinfra.
But I can't find testing for homebrew-cask.
This pr be able to express this in serverspec as:
```ruby
describe package('vagrant') do
it { should be_installed.by('homebrew_cask') }
end
describe package('vagrant') do
it { should be_installed.by('homebrew_cask').with_version('1.7.2') }
end
```
But I think this pr is not good because brew-cask can install only OSX.
I want to tell me if you have idea to test homebrew-cask. or close this pr if it is unnecessary.
> Add `should be_installed.by 'homebrew_cask'`

- lib/specinfra/command/module/service/daemontools.rb
- spec/command/module/service/daemontools_spec.rb
Needed a small fix for https://github.com/serverspec/specinfra/pull/387
`[ -d log ] && svc -d log` exits with code 1 if `log` directory does not exist.
`svc -dx . log` outputs
```
svc: warning: unable to chdir to log: file does not exist
```
but, its exit code is 0. Let us use `svc -dx . log`.
https://github.com/hirose31/chef-provider-service-daemontools/blob/1a2aeb34cb604d637539601c1e0de8fec596be3c/lib/chef/provider/service/daemontools.rb#L58 is doing the same thing.
> Fix disable_under_daemontools

- lib/specinfra/backend/ssh.rb
- lib/specinfra/configuration.rb
Hi, I've add ssh_without_env option to configration.
Example of usage following.  
```
require 'spec_helper'
describe command('sudo -i -u vagrant locale') do
let(:ssh_without_env) { true }
its(:stdout) { should match "en_US.UTF-8" }
end
describe command('sh -l -c "locale"') do
its(:stdout) { should match "C" }
end
describe command('sh -l -c "locale"') do
its(:stdout) { should match "C" }
end
#=>
Command "sudo -i -u vagrant locale"
stdout
should match "en_US.UTF-8"
Command "sh -l -c "locale""
stdout
should match "C"
Command "sh -l -c "locale""
stdout
should match "C"
Finished in 0.77259 seconds (files took 5.72 seconds to load)
3 examples, 0 failures
```
> add config ssh_without_env to skip sending envs

- lib/specinfra/helper/os.rb
`detect_os`の処理で検出を全部抜けると、戻り値が`Specinfra::Helper::DetectOs.subclasses`の結果(Array)になるけどもそのまま進んでしまいます。そのあと、command_factoryまで行ってこけてしまう。
ひとまず例外を出してメッセージを表示するのはどうでしょう。
> rails when failed os detection

- appveyor.yml
https://github.com/serverspec/serverspec/pull/520 と一緒です。
Appveyorが引っ張った時、それぞれ次のような組み合わせでGemがつかわれる(はず)という仕様です。
- Specinfra
- Serverspec: github/master
- Specinfra: CI対象のソース
- Serverspec
- Serverspec: CI対象のソース
- Specinfra: github/master
> Integration test for winrm with appveyor

- lib/specinfra/command/windows/base/process.rb
Enables things such as:
```ruby
describe process("powershell.exe") do
it { should be_running }
its(:user) { should eq('vagrant') }
end
```
It didn't appear necessary to reimplement `check_is_running` in order to be able to use `be_running`.
> Implement Process::get on Windows

- lib/specinfra/command/module/service/daemontools.rb
- spec/command/module/service/daemontools_spec.rb
Ubuntu puts the service dir in /etc/service, so fall back to this directory if /service does not exist
> Support daemontools service dir in /etc

- lib/specinfra/command/freebsd/base/file.rb
* 'sha256' require FreeBSD 7.0-RELEASE later.
> support matcher 'md5sum' and 'sha256sum' on FreeBSD.

- lib/specinfra/command/windows/base/registry_key.rb
- Currently we always try to convert assuming the value is of they type   passed instead of the literal value it should be, this would allow 	the user to skip the convert as it is the expected literal value
> (maint) Allow users to specify _converted suffix type 

- lib/specinfra/command/base/file.rb
- spec/command/base/file_spec.rb
These checks add to the ability of the file resource. It allows you to check if the specified device is a block device and/or a character device.
> Add checks for block_device and character_device

- lib/specinfra/host_inventory/filesystem.rb
- spec/host_inventory/filesystem_spec.rb
I refactored host_inventory/filesystem.rb so that I could write a unit test for it. The unit test is under spec/host_inventory/filesystem_spec.rb
> Adding unit test for host_inventory/filesystem and refactoring it sligthly

- lib/specinfra/helper/detect_os/aix.rb
uname -rvp yields minor_release, major_release and architecture on AIX. Tested the code against an AIX 6.1 and 7.1 machine. The previous code displayed the machine ID number instead of the architecture (uname -m). With this fix the architecture is set to 'powerpc' on the hosts tested.
> Modifying the AIX detect_os code to include the release and architecture

- lib/specinfra/host_inventory/domain.rb
- lib/specinfra/host_inventory/fqdn.rb
- lib/specinfra/host_inventory/hostname.rb
I encountered that `domain` is set to `dnsdomainname: Name or service not known`. IMO, host inventory should return `nil` in such situation.
> domain, fqdn and hostname inventory value returns nil if it fails.

- lib/specinfra/command/base/group.rb
The current `check_has_gid` function does not work universally. It fails on systems that cannot enumerate all groups on the system, such as those that use directory services to store user and group databases. This PR fixes this bug.
> fix check group gid method

- lib/specinfra/helper/detect_os/darwin.rb
While this is not the MacOS release number for such a case a new key like friendly_name or such some is needed.
> Adding darwin kernel release number

- lib/specinfra/helper/detect_os/freebsd.rb
> detect_os/freebsd: Make release check more universally applicable

- specinfra.gemspec
net/telnet will be removed from Ruby 2.3.
https://bugs.ruby-lang.org/issues/11083
> Add net-telnet dependency

- lib/specinfra/command/module/service/systemd.rb
- spec/command/module/service/systemd_spec.rb
- spec/command/module/systemd_spec.rb
There's many extensions for systemd units: .timer, .swap, .path, and so
on. The only stable way is to use `systemctl is-enabled` command.
> systemd: Check by is-enabled subcommand

- spec/helper/detect_os/aix_spec.rb
- spec/helper/detect_os/darwin_spec.rb
- spec/helper/detect_os/freebsd_spec.rb
For testing the os detetction code in aix, darwin and freebsd.
> spec/detect_os: Adding spec files for aix, darwin and freebsd

- lib/specinfra/command.rb
- lib/specinfra/command/freebsd/base/user.rb
- lib/specinfra/command/freebsd/v6.rb
- lib/specinfra/command/freebsd/v6/user.rb
- lib/specinfra/version.rb
FreeBSD old version don't have 'getent'.
It was imported into FreeBSD 7.0.
* check_has_home_directory
* check_has_login_shell
* get_home_directory
* get_login_shell
* get_encrypted_password
Use 'grep' instead of 'getent'
Test at FreeBSD 4.11 and 8.4
> Support user.rb in the Old FreeBSD.

- lib/specinfra/command/linux/base/file.rb
- spec/command/linux/file_spec.rb
The previous code did only work when _only_ the immutable flag was set.
When other attributes were added, although the file was still immutable,
it would return exit status 1.
This patch fixed the behaviour as outlined below.
Before:
'suS-iadAcj-t-e- /var/tmp/immutable' returns failure despite the presence of 'i'
'----i---------- /var/tmp/immutable' returns success which is correct
'suS--adAcj-t-e- /var/tmp/immutable' returns failure which is correct
With fix:
'suS-iadAcj-t-e- /var/tmp/immutable' returns success correctly as 'i' is present
'----i---------- /var/tmp/immutable' returns success correctly as 'i' is present
'suS--adAcj-t-e- /var/tmp/immutable' returns failure correctly as 'i' is not present
> linux/check_attribute: fix failure when many attribs are set

- lib/specinfra/command.rb
- lib/specinfra/command/freebsd/base/user.rb
- lib/specinfra/command/freebsd/v6.rb
- lib/specinfra/command/freebsd/v6/user.rb
This PR is replace from #426 
FreeBSD old version don't have 'getent'.
It was imported into FreeBSD 7.0.
* check_has_home_directory
* check_has_login_shell
* get_home_directory
* get_login_shell
Use 'pw' instead of 'getent'
Test at FreeBSD 4.11, 8.4 and 7,3.
> Old FreeBSD can use have_home_directory and have_login_shell

- lib/specinfra/backend/exec.rb
- specinfra.gemspec
With the previouse way, if a grandchild process holds stdout or stderr,
the command hangs up.
I've changed the way to run command to fix it.
As a side effect, we can get sttderr correctly with exec backend.
> Change how to run command with exec backend

- lib/specinfra/backend/docker.rb
If set only ```Entrypoint``` instead of ```Cmd``` in Dockerfile, when start the container "/bin/sh" is passed as a parameter of ```Entrypoint``` by specinfra. There is a case to fail to start the container.
For this problem, check whether nil the ```Cmd``` and ```Entrypoint``` before you create a container
> Add check for Entrypoint configuration to docker backend

- lib/specinfra/helper/detect_os/darwin.rb
- spec/helper/detect_os/aix_spec.rb
- spec/helper/detect_os/darwin_spec.rb
- spec/helper/detect_os/esxi_spec.rb
- spec/helper/detect_os/freebsd_spec.rb
Small cleanups and standardizations around the unit tests, Plus making the darwin os detection cope with bogus input.
>  detect_os: Better error handling for darwin and updated specs

- lib/specinfra/backend/base.rb
- lib/specinfra/backend/exec.rb
- lib/specinfra/backend/ssh.rb
You can define your stdout and stderr handler like this.
```ruby
backend = Specinfra::Backend::Exec.new
backend.stdout_handler = Proc.new {|out| $stdout.write out }
backend.stderr_handler = Proc.new {|err| $stderr.write err }
backend.run_command('ls -al')
```
> Support custom stdout and stderr handler

- specinfra.gemspec
Oterwise it will fail with older versions missing :send_env option
> Require net-ssh of minimum 2.7

- lib/specinfra/backend/exec.rb
Sometimes outputs seems to be truncated randomly. Increasing max size of read_nonblock() seems to fix this problem.
> Increase max size of read_noblock() to avoid truncating of output

- lib/specinfra/host_inventory/virtualization.rb
I've added new virtualisation system value in  `host_inventory` such as openstack, vmware and virtualbox, because I want to use serverspec tests for different virtualisation environment.
> Add openstack, vmware and vbox to virtualisation inventory value

- lib/specinfra/host_inventory/virtualization.rb
- spec/host_inventory/linux/virtualization_docker_spec.rb
- spec/host_inventory/linux/virtualization_kvm_spec.rb
Added KVM to the virtualization host_inventory. Plus adding a two new test cases for docker and KVM.
Specifically for docker I put a return after it is detected successfully should speed up the process a bit.
> host_inventory/virtualization: Adding KVM + unit test for kvm & docker

- lib/specinfra/command/base/file.rb
- spec/command/base/file_spec.rb
This is a little opinionated feature.
I'd like to use it to update `remote_file` resource of [Itamae](https://github.com/itamae-kitchen/itamae) like following:
```ruby
remote_file '/path/to/file' do
source 'http://path.to/file' # network download
end
```
> Add download-file to base commands

- lib/specinfra/command/debian/base/service.rb
Chef comments the 'start on' line when disabling upstart services. For example:
```
service 'rsyslog' do
action :disable
end
```
... results in:
```
...
description	"system logging daemon"
#start on filesystem
stop on runlevel [06]
...
```
This change modifies the regex to only match lines that start with (some optional whitespace and) the 'start on' statement.
> Modify regex to skip commented 'start on' statements for upstart services

- appveyor.yml
Appveyorで通らなくなっていたので、Set-ExecutionPolicy行を消しました。
ひと通り走るようになりました。
https://ci.appveyor.com/project/serverspec-windows-integration-test/specinfra
> remove Set-ExecutionPolicy. no longer need on the appveyor.

- Rakefile
I think _host_inventory_ rake job should be also recursive.
Before this change:
```
$ rake spec:host_inventory
Finished in 0.00057 seconds (files took 0.07158 seconds to load)
0 examples, 0 failures
```
After the change:
```
$ rake spec:host_inventory
Finished in 0.06071 seconds (files took 0.49513 seconds to load)
78 examples, 0 failures
```
> rake task host_inventory should be recursive

- lib/specinfra/command/module/ss.rb
- spec/command/module/ss_spec.rb
Currently users which want to verify that ports are listening to `tcp6` or `udp6` connections are not able to steadily verify that as the output generated by the `ss` command in the codebase is the same for both `tcp/udp` and `tcp6/udp6`.
This PR should make a distinction and allow Serverspec tests like:
```
describe port(80) do
it { should_not be_listening.with('tcp6') }
it { should_not be_listening.with('udp6') }
end
```
to pass when such capabilities are disabled (like when managed through `sysctl`, etc).
> Distinguish between IPv4 and IPv6 lookups

- lib/specinfra/command/freebsd/base/interface.rb
- lib/specinfra/command/linux/base/interface.rb
- lib/specinfra/command/openbsd/base/interface.rb
- spec/command/freebsd/interface_spec.rb
- spec/command/linux/interface_spec.rb
- spec/command/openbsd/interface_spec.rb
The interface code for the freebsd and openbsd was slightly out of touch with the already existing linux one. Adjusted it to work the same way.
Unit tests for freebsd and openbsd are included. Plus expanded the linux ones.
Note: I think a construct like 'its(:ipv6_address) { should match /fe80::/ }' for the interface is more flexible, I'll probably add it in the near future.
> interface: Ensure same results for *bsd as for linux

- lib/specinfra/command/ubuntu/base/service.rb
Because, `service postgresql status` not return "running"
~~~
$ sudo service postgresql status
9.3/main (port 5432): online
~~~
> Fixed check_is_running is not work for postgresql-9.3 on Ubuntu 14.04.3

- lib/specinfra/command.rb
- lib/specinfra/command/openbsd/base/service.rb
- lib/specinfra/command/openbsd/v57.rb
- lib/specinfra/command/openbsd/v57/service.rb
- spec/command/openbsd/service_spec.rb
- spec/command/openbsd57/service_spec.rb
This puts back the change that 159b463a reverted to use `rcctl` as the enabled check didn't work at all for any service I've tried on 5.7. However the invocation should be `rcctl get foo status` rather than `rcctl status foo`.
> Fix OpenBSD service checks

- lib/specinfra/command/ubuntu/base/ppa.rb
- spec/command/ubuntu/ppa_spec.rb
opscode-cookbooks/apt surrounds PPA URLs with quotes (https://github.com/opscode-cookbooks/apt/blob/master/providers/repository.rb#L121). This adds an optional quote to the regex so that a PPA  added by said cookbook will pass the test.
> ubuntu/ppa: Allow quotes

- lib/specinfra/command/ubuntu/base/ppa.rb
- spec/backend/exec/build_command_spec.rb
- spec/command/ubuntu/ppa_spec.rb
This fixes mizzy/specinfra#466. The backslashes and quotes were causing escaping issues.
> Fix quote escaping for Ubuntu PPA regex

- lib/specinfra/command/darwin/base/host.rb
- spec/command/darwin/host_spec.rb
This is a small fix to dig command. This ensures dig behaves exactly like nslookup and is considering the /etc/resolv.conf's domain or search lines.
> host: Adding the +search to dig if a non-fqdn is passed to it.

- lib/specinfra/command.rb
- lib/specinfra/command/darwin/base/process.rb
- spec/command/darwin/process_spec.rb
The -C switch in the BSD-flavored version of `ps` in OS X doesn't do
what it does in Linux:
```
-C      Change the way the CPU percentage is calculated by using a
``raw'' CPU calculation that ignores ``resident'' time (this normally
has no effect).
```
```
$ ps -C Google\ Chrome -o pid= | head -1
ps: illegal argument: Google Chrome
```
This causes tests for `process('AppName')` resources to fail. This workaround
does get ugly, but yields the expected output:
```
$ ps -A -c -o command | grep Google\ Chrome
Google Chrome
Google Chrome Helper
Google Chrome Helper
```
```
$ ps -A -c -o pid=,command | grep -E -m 1 ^\ *[0-9]+\ +Google\ Chrome$
99159 Google Chrome
```
```
$ ps -A -c -o pid=,command | grep -E -m 1 ^\ *[0-9]+\ +Google\ Chrome$ | \
awk '{print $1}'
99159
```
> Don't try to use the -C switch for ps in OS X

- lib/specinfra/command/base/file.rb
Previously, `check_is_linked_to('hoge', 'foo')` returns true wrongly
when "hoge" is linked to "foobar", "foobaz", etc.
> Fix check_file_is_linked_to

- lib/specinfra/backend/ssh.rb
When running against a bunch of hosts where some of the hosts have some other password for you can be frustrating.  I thought it might be useful for the error message to tell you which host it was on, at least.
> Let us know on which host our sudo password is incorrect.

- lib/specinfra/command/linux/base/inventory.rb
- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/block_device.rb
- spec/command/linux/inventory_spec.rb
- spec/host_inventory/linux/block_device_spec.rb
Like ohai, `block_device` collects data of `/sys/block/<dev>`.
This inventory stores the same result as [`block_device` of Ohai v8.6.0](https://github.com/chef/ohai/blob/v8.6.0/lib/ohai/plugins/linux/block_device.rb).
> Collect block device of host inventory

- lib/specinfra/command/freebsd/v10/package.rb
pkg info -e return 0 or 1: suitable for this use.
https://www.freebsd.org/cgi/man.cgi?query=pkg-info&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html
> use `pkg info -e`

- lib/specinfra/command/fedora/base/service.rb
- lib/specinfra/command/freebsd/base/user.rb
- lib/specinfra/command/openbsd/base/service.rb
- lib/specinfra/command_factory.rb
Some commands see `os` (lib/specinfra/helper/os.rb) on creation,
which referes Specinfra.configuration.os or Specinfra.configuration.backend.
But it doesn't work on multiple backends (examples/multiple_backends.rb)
or Serverkit.
> Pass os_info to command_class.create

- lib/specinfra/backend/powershell/support/is_port_listening.ps1
Specinfra doesn't detect ports that are listening on localhost on Windows, because no adapter lists 127.0.0.1 as one of its active addresses. This manually adds it to the list of addresses to check.
> Check localhost for listening ports on Windows.

- lib/specinfra/backend/powershell/command.rb
The global substitution in the powershell command match is eating potentially useful forward slash characters.
Full detail at https://github.com/chef/chef-dk/issues/526
> Allow forward slashes within PS literal

- lib/specinfra/command/windows/base/file.rb
Specinfra didn't implement file exist check command on Windows.
So, add check_exists method.
before example: 
```
describe file("C:\\Windows") do
it { should exist }
end
```
-->
```
~
1) File "C:\Windows" should exist
On host `localhost'
Failure/Error: it { should exist }
NotImplementedError:
check_exists is not implemented in Specinfra::Command::Windows::Base::File
~
```
after example:
```
describe file("C:\\Windows") do
it { should exist }
end
```
-->
```
~
File "C:\Windows"
should exist
~
```
> Support check_file_exists method on Windows

- lib/specinfra/backend/docker.rb
After I do something command , image when the send_file from being initialized .
I have to fix this problem .
```
require 'specinfra'
require 'docker'
Excon.defaults[:ssl_verify_peer] = false
@backend = Specinfra::Backend::Docker.new(docker_image:'centos:7')
@backend.run_command('touch /tmp/aaaaa')
@backend.run_command('ls /tmp/aaaaa').exit_status
@backend.send_file 'Gemfile', '/tmp/Gemfile'
@backend.run_command('ls /tmp/Gemfile').exit_status
@backend.run_command('ls /tmp/aaaaa')
```
> Commit docker container before send_file.

- lib/specinfra/backend/docker.rb
I want to execute sudo with Specinfra::Backend::Docker#run_command.
```
require 'specinfra'
require 'docker'
Excon.defaults[:ssl_verify_peer] = false
@backend = Specinfra::Backend::Docker.new(docker_image:'centos:7')
@backend.run_command('yum install -y sudo')
@backend.run_command('sudo -H -u root -- /bin/sh -c cd /tmp/ && ls -l')
```
So I modified.
```
@backend.run_command('sudo -H -u root -- /bin/sh -c cd /tmp/ && ls -l', { tty: true })
```
> Added opts to execute run_command and docker_run!

- lib/specinfra/command/base/mail_alias.rb
- spec/command/base/mail_alias.rb
Currently entries in the /etc/alias file that look like this
myalias:     foo, bar, batz
can only be parsed in the exact order:
describe mail_alias('myalias') do
it { should be_aliased_to('foo, bar, batz') }
end
If the order changes or more white space is added the whole thing falls apart.
Replacing the $ with (,|$) at the end of the egrep allows for more flexibilty:
describe mail_alias('myalias') do
it { should be_aliased_to('batz')
it { should be_aliased_to('foo')
it { should be_aliased_to('bar')
end
The order becomes irrelevant.
This scheme has been tested against the following patterns:
myalias:         foo, bar, batz
myalias:         foo, bar, batz
myalias:         foo , bar , batz
myalias:         foo
myalias:         /foo/bar, /bar/foo
myalias:         "|/foo/bar", '|/bar/foo' …
> mail_alias: Replacing the trailing $ with (,|$) to match single entries

- lib/specinfra/configuration.rb
`Helpet::DetectOS#os` in the comment seems to be a typo of `Helper::DetectOS#os`.
I fixed it.
> Fix a typo in the comment for Configuration#os

- lib/specinfra/command.rb
- lib/specinfra/command/raspbian.rb
A new class Specinfra::Command::Raspbian is now required for Raspbian Jessie (Linux distribution for Raspberry Pi compatible with Debian v8) because `lsb_release -ir` returns `Raspbian` as the Distributor ID.
Specinfra raises a `NameError: uninitialized constant Raspbian` without creating this class.
> Supports Raspbian Jessie

- lib/specinfra/command/redhat/base/package.rb
In RedHat and its clone, not only a packaged software version but also a
package release number are used for checking newer package availability.
This changes RPM version to include a release number.
I don't know much about SUSE package's version policy so only fix RedHat one.
> Include RPM release in package version

- lib/specinfra/command/base/user.rb
This PR adds support for group names with spaces, for example in an environment that used a Windows domain for authentication and authorization.
Example on a RHEL7 server:
```
[jfolmer@host06 infratests]$ id
uid=1616201105(jfolmer) gid=1616200513(domain users) groups=1616200513(domain users) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
Previously:
```
[jfolmer@host06 infratests]$ id |awk '{print $3}'
users)
[jfolmer@host06 infratests]$ 
```
Improved command:
```
[jfolmer@host06 infratests]$ id |sed 's/ context=.*//g' |awk -F= '{print $4}'
1616200513(domain users)
[jfolmer@host06 infratests]$ 
```
> belong_to_group: support for group names with spaces

- lib/specinfra/backend/ssh.rb
When pty is allocated and host name is not set, the error message "sudo: unable to resolve host" is injected into stdout and it brings unexpected behavior.
So exclude this error message from stdout.
> Exclude sudo error message from stdout

- lib/specinfra/command/redhat/base/yumrepo.rb
If you have different repos with name like gvp-bi-common, gvp-bi-common-x86_64, gvp-bi-common-noarch, etc...and we want to verify that gvp-bi-common-x86_64 and gvp-bi-common-noarch exists and gvp-bi-common NOT exists, with the current code it fails because we have 2 repos with the same starting string so it matches that the repo exists. Using a regexp at the check make it behaves correctly.
> Use regexp to match exactly the repo name

- lib/specinfra/processor.rb
...instead of `stopping/waiting`.
> It appears some versions of upstart give `stop/waiting`.

- lib/specinfra/command/darwin/base/package.rb
I fixed `Specinfra::Command::Darwin::Base::Package` to support:
- custom brew prefix
- It can be non-"/usr/local" path and checked by only `brew --prefix`
- proper check for "user/repo/formula" style installation
- If `foo/bar/hoge` is given, use basename (hoge) to check existence
And I optimized it too. Since `brew list` and `brew info` are slow, I replaced them using `ls`.
This is the time spent on 30 brew packages installation by itamae (with all packages installed beforehand)
```
14.94s user 5.85s system 97% cpu 21.262 total
```
```
rake  4.68s user 1.87s system 99% cpu 6.556 total
```
> Allow custom brew prefix

- Gemfile
- specinfra.gemspec
net-ssh 3.0.x has no breaking changes to do with specinfra.
https://github.com/net-ssh/net-ssh/blob/v3.0.1/CHANGES.txt
> Allow net-ssh 3.0.x

- lib/specinfra/backend/base.rb
When executing ServerSpec examples in the same process using `RSpec::Core::Runner.run` we need some way to clear the test suite state so the configuration for the previous tests does not impact on further test runs.
Within RSpec there is a [clear_examples](https://relishapp.com/rspec-staging/rspec-core/docs/running-specs-multiple-times-with-different-runner-options-in-the-same-process) method to do this. Within ServerSpec the problem is the backend connection is being re-used between runs and so even though we change the `host` we are in fact connecting to the host from the first test run.
This PR adds a mechanism to clear the backend, so it does not interfere with multiple runs.
> Adds class method to clear backend

- lib/specinfra/command/cumulus.rb
- lib/specinfra/command/cumulus/base.rb
- lib/specinfra/command/cumulus/base/ppa.rb
- lib/specinfra/command/cumulus/base/service.rb
- spec/command/cumulus/ppa_cumuluslinux_spec.rb
- spec/command/cumulus/ppa_cumulusnetworks_spec.rb
/etc/lsb-release on cumulus linux changed from "cumulus networks" to "cumulus linux" in a recent version. this ensures serverspec works with the latest release of Cumulus Linux.
> Update Cumulus Linux support files

- lib/specinfra/command/base/process.rb
- spec/command/base/process_spec.rb
I have added a `count` method to Specinfra::Command::Base::Process and unit tests for this method.
> Added methods to count number of running processes

- lib/specinfra/command/ubuntu/v15.rb
This should fix a bug on Ubuntu 15.04 (and probably 15.10, 15.x also) where the PPA resource does not work.
Error message due to this bug looks like:
```
1) foobar::default Ppa "foobar/ppa" should exist
Failure/Error: it { should exist }
NotImplementedError:
check_exists is not implemented in Specinfra::Command::Debian::Base::Ppa
/bin/sh -c uname\ -m
x86_64
2) foobar::default Ppa "foobar/ppa" should be enabled
Failure/Error: it { should be_enabled }
NotImplementedError:
check_is_enabled is not implemented in Specinfra::Command::Debian::Base::Ppa
```
Error seems to be caused by the class `Specinfra::Command::Ubuntu::V15` inheriting from `Specinfra::Command::Debian::Base` instead of `Specinfra::Command::Ubuntu::Base`.
The PPA resource is not defined in the class …
> Fix PPA resource on Ubuntu 15.04

- specinfra.gemspec
net-ssh 3.0 dropped support for Ruby < 2.0 causing an issue for
test-kitchen/busser: https://github.com/test-kitchen/busser/issues/32
In summary, older versions of Chef use Ruby < 2.0. When running kitchen
tests with busser-serverspec, it tries to install the serverspec gem,
attempts to install the latest allowable net-ssh (3.0.x) and fails as it does
not support Ruby < 2.0.
> Restrict net-ssh to < 3.0 for Ruby < 2.0

- specinfra.gemspec
On closer look, it was net-ssh [2.10](https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt#L25) that dropped support for Ruby < 2.0
Following up from #513
> Correction to net-ssh version for Ruby < 2.0

- lib/specinfra/command/freebsd/base/file.rb
get_mode function always returns "0".
It is the result of .oct method of string "stat ..."
To follow linux stat command,
cut "0" letters at the begging of result of stat command.
> Fix stat command line to follow linux behavior.

- lib/specinfra/command/freebsd/base/service.rb
- lib/specinfra/command/freebsd/base/user.rb
Avoid using third party commands of FreeBSD.
'service status' sub-command is supported in rc.subr framework.
'pw' command is offered to add/del user/groups .
> Fix command freebsd

- lib/specinfra/command/arch/base/package.rb
While I want to install Arch packages in base-devel group with just writing `package 'base-devel'` in itamae recipe, we can't check whether the group is installed or not by `pacman -Q`. To check package group, I changed `check_is_installed` to check `pacman -Qg` too.
Since package group itself does not have version, I didn't care about version for package group in this change.
> Check arch package installation for group too

- lib/specinfra/command/debian/v8/service.rb
Hi, mizzy-san. This patch is to fix `check_service_is_enabled_under_systemd` on Debian 8.
Debian 8.x "jessie" has problem on Systemd's SysV compatibility that invoking `systemctl is-enabled $SERVICE` on a SysV service always fails. Due to this problem Specinfra fails to correctly check whether the service is enabled.
This patch resolves the problem by "backporting" the checking mechanism from Debian "testing".
The next Debian major release will likely to fix the problem by adopting `systemd-sysv-install`, which is an abstraction layer for SysV services management tools such as `update-rc.d`. Its implementation[1] for Debian has a command to test if a SysV service is enabled.
```sh
ls $ROOT/etc/rc[S5].d/S??$NAME >/dev/null 2>/dev/null
```
This patch makes …
> Fix check_service_is_enabled_under_systemd for Debian jessie

- lib/specinfra/backend/exec.rb
- lib/specinfra/configuration.rb
- spec/backend/exec/build_command_spec.rb
I've run into several instances where I need a file(s) in `/etc/profile.d` to be loaded before running a test case. Unfortunately, these files are only included in interactive shells. Rather than hard coding paths and building convoluted `:pre_command` or command examples, it would be easier if Specinfra could emulate an interactive shell and load these files automatically.
> Add the option to emulate an interactive interactive shell

- appveyor.yml
No longer needed this rule.
And, this PR will solves https://ci.appveyor.com/project/serverspec-windows-integration-test/specinfra/build/337/job/p329fqqq30aaadcb because updating appveyor.yml will purge older caches.
> Remove ruby22 from allow_failures on appveyor

- lib/specinfra/command/redhat/base/yumrepo.rb
Commit 35f6f6bf only fixed the enabled check. Exist check also needs to support the same output format. See yum(8) repolist documentation for details on '*' and '!' prefix in first column.
> yumrepo: Support non-verbose mode(*) and old metadata(!)

- lib/specinfra/command/windows/base/service.rb
- spec/command/windows/service_spec.rb
Hey mizzy,
I am currently working with windows based machines and wanted to add support for windows service properties. I have added a method for check_has_property and get_property. I have also added a set of test for Windows Service Commands. If you see anything in my code that needs adjustment just tell me and I will change it. 
Also, Should I be using "expect" or "should" in the test?
Thanks
-Charlie
> Windows service properties support

- lib/specinfra/backend/exec.rb
- lib/specinfra/configuration.rb
- spec/backend/exec/build_command_spec.rb
In #520, `:interactive_shell` option (which adds `-i` option to shell) was added,
but I need to add `-l` option to shell to load files in `/etc/profile.d` on my environement.
So I want to add `:login_shell` option to specinfra.
> Added option to emulate a login shell

- lib/specinfra/command/windows/base/service.rb
started getting error:
```
Fetching: specinfra-2.51.2.gem (100%)
Successfully installed specinfra-2.51.2
Parsing documentation for specinfra-2.51.2
RDoc::Parser::Ruby failure around line 52 of
lib/specinfra/command/windows/base/service.rb
"\n    end\n  end\nend\n"
Before reporting this, could you check that the file you're documenting
has proper syntax:
/opt/chef/embedded/bin/ruby -c lib/specinfra/command/windows/base/service.rb
RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.
The internal error was:
(RDoc::RubyLex::Error) Missing terminating (FindService -name '#{service}').#{key} -eq '#{value}' for string
ERROR:  While executing gem ... (RDoc::RubyLex::Error)
Missing terminating (FindService -name '#{service}').#{key} -eq '#{value}' for string
```
> fix syntax error in array push operator

- lib/specinfra/command/darwin/base/interface.rb
- lib/specinfra/command/freebsd/base/interface.rb
- lib/specinfra/command/linux/base/interface.rb
- lib/specinfra/command/openbsd/base/interface.rb
- spec/command/darwin/interface_spec.rb
- spec/command/freebsd/interface_spec.rb
- spec/command/linux/interface_spec.rb
- spec/command/openbsd/interface_spec.rb
I have a situation where I have over ten thousand linux servers that each fit into one of four roles.  Each of these four roles has ipv4 interfaces and interface aliases that fit a regular expression by role and interface.  I need to be able to test for this.  This is a precursor to a future serverspec PR.
> adding new get_interface_ipv4/v6_address feature

- lib/specinfra/command/base/cron.rb
This PR is to fix Serverspec fails in case backslash exists in crontab.
For example,
```
* * * * * touch /tmp/file.`date +\%Y\%m\%d`
```
> Allow backslash in crontab

- lib/specinfra/command/windows/base/file.rb
The Windows implementation of `is_owned_by` failed all the time because it returned 0 and 1 in the command but `ScriptHelper#create_script` checks for a `Boolean` value.
> Return $TRUE and $FALSE in Windows is_owned_by command

- lib/specinfra/command/base/file.rb
- spec/command/base/file_spec.rb
This pull request is reference to [itamae-kitchen/itamae#191](https://github.com/itamae-kitchen/itamae/pull/191).
- Add `-p` option to `copy` to preserve attributes.
- Add `-R` option to `copy` to copy a directory.
- Add `-R` option to `change_mode`, `change_owner` and `change_group`.
> Add options to Command::Base::File

- lib/specinfra/backend/docker.rb
This PR allows Docker backend to send file from local to running container.
Since Docker 1.8, we can copy file from local to container. I use this feature in this PR.
(Ref) https://blog.docker.com/2015/08/docker-1-8-content-trust-toolbox-registry-orchestration/
Could you check and merge it if you think OK?
> Docker backend accepts send_file when base_image isn't set, but container is set

- lib/specinfra/command/windows/base/file.rb
`Out-String` introduces extra line breaks in the content, whereas `Write-Host` does not. I had a test to verify the content of a file that had a line longer than 80 characters. The test was failing because the content grabbed by `Get-Content | Out-String` included a newline that is not in the actual content. Switching to `Write-Host` eliminated the extra newline.
> Use Write-Host instead of Out-String for Windows file content

- lib/specinfra/command.rb
- lib/specinfra/command/sles.rb
- lib/specinfra/command/sles/base.rb
- lib/specinfra/command/sles/v12.rb
- lib/specinfra/command/sles/v12/service.rb
- lib/specinfra/helper/detect_os/suse.rb
- spec/helper/detect_os/suse_spec.rb
From SLES 12 onward, the default init system became systemd and thus needs a fix here to correctly define the init system. I did some very light acceptance testing with SLES 12 and OpenSuSE 13 to verify things are sane. Added some tests as well.
I am **very likely** missing some things here or doing something wrong, so please advise if there are other places I need to update in the code.
This is a potentially breaking change downstream as the SuSE detection is either opensuse or sles without any plain 'suse' detection anymore, so I'm not sure if there's anything that needs to be done to mitigate that, though it does carry on the intent of #60 to specify the SLES and OpenSuSE are inherited distros from SuSE in general.
> SLES 12 Support

- specinfra.gemspec
Because net-ssh 3.1 is released and we would like to use it.  The changelog for differences between 3.0.2 and 3.1 is [here](https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt).  We have been testing with 3.1 and have yet to find any errors.
\cc @mizzy
> Allowing the use of net-ssh < 4.0 if using Ruby 2.0+

- lib/specinfra/backend/exec.rb
- spec/backend/exec/consume_exited_process_spec.rb
`Backend::Exec` can't get entire stdout or stderr due to race condition between specinfra and spawned process.
This PR will consume remained data in buffer.
These specs include `sleep 1` to raise error surely.
But, these specs will fail without `sleep` very rarely(below 1/100 on my environment)
IMHO, original code remain data cause following scenario.
1. child process write stdout and close it
2. child process write stderr
3. specinfra read from stdout and catch `EOFError`
4. exit thread although some text remain in buffer of stderr
> Consume remained stdout and stderr from buffer

- lib/specinfra/command/base/package.rb
- spec/command/base/package_spec.rb
Check for whether fluentd plugin is installed by td-agent-gem
```ruby
describe package("fluent-plugin-forest") do
it { should be_installed.by("td_agent_gem").with_version("0.3.0") }
end
```
> Support fluentd plugin installed check command

- lib/specinfra/command/base/user.rb
- spec/command/base/user_spec.rb
If the previous command runs like following, it doesn't work as expected
because '$6' is expanded by `sudo -i`.
It can be avoided by removing `-i` or something other way, but in thi
case using cut seems simplest.
> sudo -H -u ubuntu -i -- /bin/bash -i -c cd\ \&\&\ getent\ passwd\ ubuntu\ \|\ awk\ -F:\ \'\{\ print\ \$6\ \}\'
> Use cut instead of awk

- lib/specinfra/backend/exec.rb
During process living, those pipes are used.
> Close communication pipes after process finished

- lib/specinfra/command/base/user.rb
- spec/command/base/user_spec.rb
`cut -d SEP` gets only one character, not a string.
Pached by @eban https://twitter.com/eban/status/733663069302218752
> Use sed instead of grep and cut

- lib/specinfra/command/base/file.rb
- spec/command/base/file_spec.rb
To check that the real path of a symlink is completely resolvable. To test when there are multiple levels of symlinks.
> Add check that symlinks can be fully resolved to their real path

- lib/specinfra/host_inventory/virtualization.rb
[systemd-detect-virt](https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html) is available with systemd v183 and later.
> host_inventory: use systemd-detect-virt for virtualization detection

- Gemfile
- Guardfile
- lib/specinfra/ext/class.rb
- spec/backend/exec/build_command_spec.rb
- spec/backend/exec/child_process_spec.rb
- spec/backend/exec/consume_exited_process_spec.rb
- spec/backend/exec/env_spec.rb
- spec/backend/exec/read_noblock_spec.rb
- spec/backend/ssh/build_command_spec.rb
- spec/configuration_spec.rb
- spec/helper/detect_os/darwin_spec.rb
- spec/helper/os_spec.rb
- spec/host_inventory/linux/virtualization_spec.rb
- spec/host_inventory/openbsd/virtualization_spec.rb
- spec/host_inventory/solaris/virtualization_spec.rb
- specinfra.gemspec
It is more convenient to be able to run the specs with Guard and rspec rather
than relying on the separation of specs through rake. This PR handles setting / resetting global configurations around spec files to reduce the coupling between spec files.
I have tested running the spec suite in random order and in particular orders that failed before. E.g. running `rspec spec/backend/ssh spec/backend/exec` to show up global configurations that persist between different specs and cause each other to break.
NOTE: with the specs that are using an implicit subject from the describe group, it is not possible to use RSpec before / after hooks to set global configuration.
> Isolate specs so the whole suite can be run

- lib/specinfra/command/freebsd/base/inventory.rb
On FreeBSD, some of the SMBIOS information exported from the kernel are available through [kenv](https://www.freebsd.org/cgi/man.cgi?kenv(1)).
> host_inventory: use kenv to get the system product name on FreeBSD

- lib/specinfra/command/base/package.rb
- spec/command/base/package_spec.rb
I recently discovered when answering a question on StackOverflow that for a server with the following installed:
```
ansible-lint
puppet-lint
```
but not the following installed:
```
ansible
puppet
```
the following tests would still erroneously pass:
```ruby
describe package('ansible') do
it { expect(subject).to be_installed.by('pip') }
end
describe package('puppet') do
it { expect(subject).to be_installed.by('gem') }
end
```
This PR fixes those types of false successes.
> pip and gem check_is_installed false successes

- lib/specinfra/ext/class.rb
Ruby <= 2.0 does not have Module#singleton_class? but also seems to not
include singleton classes in the object space. Thus we don't need to check for singleton_class subclasses to skip in Ruby <= 2.0.
Check `k < self` before checking for singleton class. This is the simpler check and limits us to checking for singleton_class amongst children of the class we care about (and generally have control over).
Fixes https://github.com/mizzy/specinfra/pull/558
> Fix subclasses singleton_class check

- lib/specinfra/command/darwin/base/port.rb
- spec/command/darwin/port_spec.rb
Wanted to test if a `UDP` port was listening, but found that the `check_is_listening` for darwin doesn't handle the `:protocol` option.
Added the 4 different possibilities to the the `lsof -i` options, taken from the [man page](http://ss64.com/osx/lsof.html). Also note that `UDP` doesn't have a `LISTEN` state.
Thanks!
> Add protocol options to darwin port listening check

- lib/specinfra/command/freebsd/base/user.rb
On FreeBSD target, itamae(v1.9.8) "user resource"
failed with "system_user" option.
Cause:
pw(8) {useradd|user add} is NOTHING "-r" option
and create "system_user"(lower-range uid) option.
How to reproduce:
$ cat > system_user.rb
user "Create system user" do
action :create
username "testdaemon"
system_user true
end
^D
$ itamae ssh -l debug -u USER -h FREEBSD_HOST system_user.rb
or
$ cd /path/to/vagrant/freebsd
$ vagrant up
$ itamae ssh -l debug --vagrant system_user.rb
(snip)
INFO :       user[Create system user] exist will change from 'false' to 'true'
DEBUG :       Executing `id testdaemon`...
DEBUG :         stdout | id: testdaemon: no such user
DEBUG :         exited with 1
DEBUG :       Executing `pw user add testdaemon -r`...
DEBUG :         stdout | pw: illegal option -- r
DEBUG : …
> Ignore "system_user" option for user creation on FreeBSD.

- lib/specinfra/command/darwin/base/package.rb
Problem
---
- Caskroom now uses 2 possible locations.
- Deprecated, but still valid for older versions: /opt/homebrew-cask/Caskroom/
- New: /usr/local/Caskroom
- Serverspec didn't handle the old one, now it should.
Simply check both, this should solve an issue where a cask is installed in the new location instead of the old one.
> Cask now uses 2 separate potential files locations

- lib/specinfra/backend/docker.rb
- lib/specinfra/configuration.rb
This will enable people to configure the User that specific commands are run as.
For example, when running a set of common tests on a container, you may
also want to check that the yum caches have been properly cleared out, but
that the installed packages are all up to date.
Very simple serverspec example:
```
before(:all) do
set :docker_container_exec_options, { :user => 'root' }
end
describe command('id') do
its(:stdout) { should contain 'uid=0' }
end
after(:all) do
set :docker_container_exec_options, {}
end
```
> Provide :docker_container_exec_options similar to :docker_container_create_options

- lib/specinfra/command.rb
- lib/specinfra/command/debian/base/port.rb
- lib/specinfra/command/debian/v8/port.rb
- spec/command/debian/port_spec.rb
- spec/command/debian8/port_spec.rb
ref:#445, #453
I'm poor at english.
PR #453 would replace all debian version netstat. I believe it is a problem.
Consideration of the backward compatibility, only change to the debian jessie.
Please close this PR if my misunderstanding.
I think jessie default command is ss.
Dockerhub debian:jessie official  repository
https://github.com/tianon/docker-brew-debian/blob/8072332b0dadf2f2590292c5e545bf0f9c2320e6/jessie/build.manifest#L31
> Replace netstat with ss for Debian jessie

- lib/specinfra/command/module/ss.rb
- spec/command/module/ss_spec.rb
Without this change, "should_not be_listening.on('0.0.0.0')" using ss for a
given port (say, 53) uses the following grep:
```
ss -tunl | grep -- \ *:53\
```
This matches zero ore more spaces, followed by :53, followed by a space,
including lines such as:
```
udp    UNCONN     0      0      127.0.0.1:53                    *:*
```
It should be (note the additional backslash):
```
ss -tunl | grep -- \ \*:53\
```
This matches a space followed by an asterisk, followed by :53, followed by
space, which is correct as it only matches lines such as:
```
udp    UNCONN     0      0              *:53                    *:*
```
> Escape asterisk in grep so it's not interpreted as zero or more spaces

- lib/specinfra/backend/docker.rb
Opened as a WIP (Need to familiarise with the docker API for ruby).
The idea is to remove the need of work around #545 and rely on the provided [healthcheck system](https://docs.docker.com/engine/reference/builder/#/healthcheck) to ensure that a container has been started entirely before running the rspec tests.
> Use the healthcheck system to wait for the container to be ready

- specinfra.gemspec
This attribute could be used from some external tools, scripts, or services (in my case, an rbenv plugin named [gem-src](https://github.com/amatsuda/gem-src)).
> 🏠 Set homepage URL to the gemspec

- appveyor.yml
using latest image !
- show PSVersionTable for debug
- use newer image
- ref: http://help.appveyor.com/discussions/problems/5170-progresspreference-not-works-always-shown-preparing-modules-for-first-use-in-stderr
- remove os section
> fix appveyor fails

- lib/specinfra/helper/detect_os/eos.rb
- spec/helper/detect_os/eos_spec.rb
64d8587c13405b0ca0661e5214e98575e5744bd9 caused issues with some tests.  Backing off to just "eos" as the family.
> Change Arista EOS family to just 'eos'

- lib/specinfra/helper/detect_os/debian.rb
- spec/backend/exec/build_command_spec.rb
- spec/helper/detect_os/debian_spec.rb
This isn't possible on Ubuntu, but we can try to detect debian versions
without relying on lsb-release packages.
> Detect debian versions without lsb-release

- lib/specinfra/command.rb
- lib/specinfra/command/freebsd/v9.rb
- lib/specinfra/command/freebsd/v9/package.rb
- spec/command/freebsd/package_spec.rb
There are two "tool-stacks" for managing packages on FreeBSD:
- old one (pkg_add, pkg_info, etc..) - let call it "pkg" ,
- new one (pkg add, pkg info, etc..) - called "pkgng".
FreeBSD <= 9.0 provides only the old 'pkg' stack. FreeBSD >= 10.0 provides only the new 'pkgng' stack. FreeBSD > 9.0 uses either 'pkg' or 'pkgng', depending on how user configured its OS.
This patch makes specinfra to work with FreeBSD 9.3 in both situations - where the OS uses 'pkg'  or 'pkgng'. I used this patch successfully to implement acceptance tests for my puppet modules (e.g. [ptomulik-portsng](https://github.com/ptomulik/puppet-portsng), [specinfra_patch.rb](https://github.com/ptomulik/puppet-portsng/blob/master/spec/specinfra_patch.rb)).
> support pkgng on freebsd 9

- lib/specinfra/command/freebsd/v6/package.rb
- lib/specinfra/command/freebsd/v8/package.rb
- spec/command/freebsd/package_spec.rb
I've just caught it. The [pkg_add(1)] (https://www.freebsd.org/cgi/man.cgi?query=pkg_add&apropos=0&sektion=1&manpath=FreeBSD+9.1-RELEASE&arch=default&format=html) has no sub-command called ``install`` (it has no sub-commands at all) so the previous code always tried to install a package called ``install``, which obviously was failing. This PR shall fix the issue.
> fixed invocation of pkg_add (freebsd)

- lib/specinfra/command/openbsd/base/port.rb
- spec/command/openbsd/port_spec.rb
fixes the code below
```ruby
describe port(514) do
it { should be_listening.with('udp') }
end 
```
> fix port when :os is openbsd

- lib/specinfra/command/linux/base/lxc_container.rb
This is similar to LXC but libvirt-lxc containers are implemented
differently and need the libvirt tools to check existence and status.
> Libvirt LXC: allow to check for container existence and status

- lib/specinfra/command/module/service/runit.rb
Without a runit-specific test, `be_enabled` seems to fail (i.e. get the wrong answer) when asked about a runit service unless that service is also enabled via SysV as a backup.
Depends on mizzy/serverspec#580
> Add runit-enabled check

- lib/specinfra/command/base/file.rb
- spec/command/base/file_spec.rb
Hi maintainers,
I use specinfra via [Itamae](https://github.com/itamae-kitchen/itamae), and I need the `-n` (`--no-dereference`) option in the below case. So I implemented this. Could you check this?
**Case: Version management by symlink**
For example, I manage versions of google-cloud-sdk by using symlink. In the below case, I need to change the `current` symlink destination to upgrade `google-cloud-sdk-100.0.0-linux-x86_64` to `google-cloud-sdk-132.0.0-linux-x86_64`. However, now specinfra supports only `-f` option, so the new symlink is created under the `current` directory.
```
total 8
lrwxrwxrwx 1 root root   37 Oct 27 11:31 current -> google-cloud-sdk-100.0.0-linux-x86_64
drwxr-xr-x 7 root root 4096 Oct 27 11:31 google-cloud-sdk-100.0.0-linux-x86_64
drwxr-xr-x 7 root root 4096 Oct …
```
> Support no_dereference option for link_to

- appveyor.yml
- lib/specinfra/backend/winrm.rb
As per 
* https://github.com/WinRb/WinRM
* http://www.hurryupandwait.io/blog/released-winrm-gem-20-first-cross-platform-open-sourced-psrp-client-implementation
Along with https://github.com/serverspec/serverspec-integration-test/pull/16, this seems to fix the broken appveyor builds as well. (So I think this will fix the broken builds we still see with https://github.com/mizzy/specinfra/pull/584)
These are probably breaking changes for windows users of serverspec and might require some changes to the doc. (Since we need to use `WinRM::Connection` instead of `WinRM::WinRMWebService`)
I thought I would still open the PR and see...
> Port to Winrm v2

- lib/specinfra/command/base/package.rb
Would like to add ability for serverspec to test package install for embedded chef gem's, so need to allow non-standard gem_binary
> Accommodate non-standard gem_binary.

- appveyor.yml
However, 1.9.3 will be suspended until the Appveyor side is fixed.
> Green comes back to Appveyor

- lib/specinfra/command/linux/base/selinux.rb
- spec/command/linux/selinux_spec.rb
At the moment, when you disable SELinux in a running environment you have two options; set the current mode to 'permissive' and disable selinux within the config file (eg. /etc/selinux/config) or disable selinux and reboot the server.
Latter approach creates a lot of unnecessary work, like restarting the server and waiting for it to come back, especially with tools like Ansible, Chef etc. So I think former approach works best in an automated environment; disable selinux from the config file and set its current mode to permissive then test it.
I've changed the shell commands to check for current mode to be permissive and the mode in config is disabled, **only if** we're testing for disabled selinux mode. It should return true when these conditions are met.
Let me know what you think. …
> SELinux disabled mode should be testable without requiring a restart

- specinfra.gemspec
Net-ssh 4.0 is no longer beta/rc and includes support for ed25519 keys and other features.
> Add support for net-ssh 4.0

- lib/specinfra/command/aix/base/group.rb
- lib/specinfra/version.rb
For AIX we faced a bug during running specinfra.
When verifying the settings of a group in AIX, specinfra reports incorrectly failures.
I adjusted the group.rb in lib/specinfra/command/aix/base and added the correct command to check the existence of a group and adjusted the check on the primary group with the correct aix command.
> bugfixed the group.rb for AIX

- Rakefile
- lib/specinfra/processor.rb
- spec/processor_spec.rb
linuxish output:
`proc on /proc type proc (rw,noexec,nosuid,nodev)`
but in FeeeBSD, mount(8) returns:
`procfs on /proc (procfs, local)`
> handle `mount(8)` for FreeBSD properly

- lib/specinfra/backend/cmd.rb
Running serverspec tests in AppVeyor does not work at the moment. Every test shows a XML error with `Preparing modules for first use.`.
There is a discussion at http://help.appveyor.com/discussions/problems/5170-progresspreference-not-works-always-shown-preparing-modules-for-first-use-in-stderr how to fix this.
But the workaround with `image: Previous Visual Studio 2015` in the `appveyor.yml` also no longer works.
See also these pull requests 
- https://github.com/WinRb/winrm-fs/pull/19
- https://github.com/chef/train/pull/152
The PR's showed me what is missing. I've added the `-NoProfile` option to the powershell call and it now works in AppVeyor even with the default image.
I've tested the change with a small patch of the `cmd.rb` in this build …
> Add -NoProfile to fix suppress "Preparing modules for first use." message

- lib/specinfra/command/debian/base/package.rb
- lib/specinfra/command/redhat/base/package.rb
- spec/command/debian/package_spec.rb
- spec/command/redhat/package_spec.rb
Fix https://github.com/itamae-kitchen/itamae/issues/238
Also, I found that the version string should be regexp escaped to be used in grep -E in `#check_is_install`. Fixed it together.
> Escape package name in package install

- lib/specinfra/backend/docker.rb
This should give access to options such as `:shell`, `:precommand`, etc. to the docker backend.
I had to give multiple goes at it.
The idea is `build_command` works fine already, no need to recreate it. There is no need to force `/bin/sh` as the shell either. The command `shellsplit` will take the command we have and execute it as expected.
Regarding the pre_command, we unfortunately can't simply do `&&` in docker (because docker runs executables, not shell, the command itself will start the shell); so instead we do two docker_run, one with the pre_command, one with the actual command.
This gives access to `:interactive_shell`, `:login_shell`, `:shell` and `:precommand`.
I haven't played with `:path`, it might be worth having something that sets an env variable in docker, but still it …
> Rely on the build command and pre-command provided by Exec

- lib/specinfra/command/debian/base/package.rb
A previous commit 8f5ad028d563371b2b59bc1e1613ae6590330942 added an extra escape to the version check for the Debian family of operating systems which broke the version check. This commit fixes that part of the commit.
Note related SO question here: http://stackoverflow.com/questions/42417864/serverspec-doesnt-check-package-version-correctly
RSpec test intentional failure shows that characters are now only being escaped once with the code update.
> Fix double escape in dpkg version check.

- lib/specinfra/command/linux/base/selinux.rb
- spec/command/linux/selinux_spec.rb
This fixes a bug introduced in d9e5721f6afa72990d408474ede0bc21ef027ca5 where the test incorrectly fails if /etc/selinux/config does not exist, when selinux is disabled.
Currently, if mode is disabled, it generates the following:
```
test ! -f /etc/selinux/config || ( (getenforce | grep -i -- disabled) || (getenforce | grep -i -- permissive) ) && grep -iE -- '^\s*SELINUX=disabled>' /etc/selinux/config
```
Expanding this out, with parenthesis to make it clearer what's going on...
```
(
test ! -f /etc/selinux/config
||
( (getenforce | grep -i -- disabled) || (getenforce | grep -i -- permissive) )
)
&&
(
grep -iE -- '^\s*SELINUX=disabled>' /etc/selinux/config
)
```
Now, it will generate:
```
test ! -f /etc/selinux/config || ( ( (getenforce | grep -i -- disabled) || (getenforce | grep -i -- …
```
> Restructures the selinux lib class, to fix the case where /etc/selinux/config does not exist in disabled mode

- lib/specinfra/helper/detect_os/suse.rb
- spec/helper/detect_os/suse_spec.rb
Before this change specinfra treats opensue 42.2 and 42.1
as the same systems but they don't.
File /etc/SuSE-release has been changed to /etc/os-release
because that file contains OS's minor and major version.
> Fix detect sles and opensuse versions.

- lib/specinfra/helper/detect_os/suse.rb
- spec/helper/detect_os/suse_spec.rb
This reverts commit ed2c16225d5162ed59a93a5219080b9ec3a20c8f, reversing
changes made to af6aa37cfce5808934a6fa483c7453a5d7c75e64.
Distributions other than suse also has /etc/os-release.
So pr610 breaks os detection mechanism.
> Revert "Merge pull request #610 from es1o/master"

- lib/specinfra/host_inventory/virtualization.rb
- spec/host_inventory/linux/virtualization_spec.rb
From this commit => https://github.com/docker/docker/commit/3b5fac462d21ca164b3778647420016315289034, the file `/.dockerinit` only used by the old and deprecated LXC execution driver. They were hacks required by docker when using LXC to run the containers.
For more info https://docs.docker.com/engine/deprecated/
> Fix host_inventory[virtualization][:system] return empty value when is a a docker container

- lib/specinfra/command.rb
- lib/specinfra/command/alpine/base/host.rb
According to the documentation in alpine
```
BusyBox v1.24.2 (2017-01-18 14:13:46 GMT) multi-call binary.
Usage: nc [OPTIONS] HOST PORT  - connect
nc [OPTIONS] -l -p PORT [HOST] [PORT]  - listen
-e PROG Run PROG after connect (must be last)
-l      Listen mode, for inbound connects
-lk     With -e, provides persistent server
-p PORT Local port
-s ADDR Local address
-w SEC  Timeout for connects and final net reads
-i SEC  Delay interval for lines sent
-n      Don't do DNS resolution
-u      UDP mode
-v      Verbose
-o FILE Hex dump traffic
-z      Zero-I/O mode (scanning)
```
In the case where protocol is `TCP` (or `tcp`), there is no `-t` option that can be used. TCP is assumed as long as `-u` isn't specified.
> Add support for TCP checks in alpine

- lib/specinfra/backend/powershell/script_helper.rb
For some historical reasons (mizzy/serverspec@4ac94006) `add_pre_command` adds the pre-command as a conditional.
This behaviour is different from the other `pre_command` systems in specinfra where the goal is to execute some code beforehand rather than applying conditions on whether or not the test is going to be executed.
This can not only lead to false positives (if the test doesn't get executed at all), but also forces the `pre_command` to return `$True`.
This changes the behaviour to follow the same pattern as the other precommands.
> Do not make the powershell pre_command a conditional

- lib/specinfra/helper/detect_os/coreos.rb
I am running serverspec test against CoreOS.
Before it was working fine for us, but recently we have updated our CoreOS from 1068.6.0 to 1235.6.0, and started failing.
We are getting following error, and we have identified that, this issue is because of CoreOS has been changed `OS_NAME` in [set_lsb_release](https://github.com/coreos/scripts/pull/620) file from just "CoreOS" to "Container Linux by CoreOS" which leads to detect_os the OS in specinfra, lib/specinfra/helper/detect_os/coreos.rb 
--------
File "/etc/passwd" should be owned by "root" 0.00067s
uninitialized constant Containerlinuxbycoreos
```
29    common_class = Specinfra::Command
30    base_class   = common_class.const_get('Base')
>> 31    os_class     = family.nil? ? base_class : common_class.const_get(family.capitalize)
32
33 …
```
> Detect os name coreos correctly

- lib/specinfra/command/redhat/base/package.rb
A previous commit f003ecf added an extra escape to the version check for the RedHat family of operating systems which broke the version check. This commit fixes that part of the commit.
See also #608 for similar situation and lead up to PR.
> Fix double escape in rpm version check.

- lib/specinfra/command/freebsd/base/routing_table.rb
> fix routing table device column of FreeBSD

- lib/specinfra/backend/jexec.rb
- lib/specinfra/command/freebsd/base/group.rb
While I'm testing Itamae FreeBSD jail support (it's under development),
I found two bugs and fixed them.
1. jail root path fix
2. command line fix which makes a new group
Please merge this pull request.
Thank you.
> Fix freebsd commands

- lib/specinfra/helper/detect_os/suse.rb
Current logic in suse.rb helper file is fetching OS info from /etc/os-release file. 
But this os-release file is not present on SUSE 11 machine so we need to have the older logic as well, which will detect the OS info from /etc/SuSE-release file.
> Updated suse.rb to detect OS info on SUSE 11 machine

- lib/specinfra/helper/os.rb
- spec/backend/exec/build_command_spec.rb
Use correct `os` variable when backend is switched to another. 
It allows to use multiple backends with Serverspec:
```ruby
require "serverspec"
require "docker"
set :backend, :docker
set :docker_container, ENV["DOCKER_CONTAINER"]
describe "Docker image" do
before(:each) { set :backend, :docker }
describe docker_image(ENV["DOCKER_IMAGE"]) do
before(:each) { set :backend, :exec }
it { is_expected.to exist }
end
describe "Operating system" do
context "family" do
subject { os[:family] }
it { is_expected.to eq(ENV["OS_FAMILY"]) }
end
context "release" do
subject { os[:release] }
it { is_expected.to eq(ENV["OS_VERSION"]) }
end
end
describe package("bash") do
it { is_expected.to be_installed }
end
end
```
> Allow to switch backends

- lib/specinfra/command/alpine/base/package.rb
`apk version` returns this information:
```bash
> apk version -U ruby-io-console
Installed:                                Available:
ruby-io-console-2.4.1-r3                = 2.4.1-r3
```
The current implementation uses the first column from which removes the text up to the first hyphen. If the package name contains a hyphen, the part of the name becomes the part of the version:
```bash
> apk version -U ruby-io-console | tail -n1 | awk '{ print $1; }' | cut -d- -f2-
io-console-2.4.1-r3
```
It would be better to use the third column which contains the version:
```bash
> apk version -U ruby-io-console | tail -n1 | awk '{ print $3; }'
2.4.1-r3
```
> get_version returns malformed value if the package name contains a hyphen

- lib/specinfra/command/alpine/base/package.rb
The current implementation only allows to test the full package version:
```ruby
describe package("ruby") do
it { is_expected.to be_installed.with_version("2.4.1-r3") }
end
```
This change will also allows to test the main version of the package:
```ruby
describe package("ruby") do
it { is_expected.to be_installed.with_version("2.4.1") }
end
```
> Allow to test main package version on Alpine Linux

- lib/specinfra/command/base/routing_table.rb
- lib/specinfra/processor.rb
Since "ip route show default" displays all the routes, "| grep #{destination}" is added in #288 .
However, with this change the results are incorrect in the case of multipath.
Therefore, when the destination is "default", only the default route is displayed by changing the destination to "0.0.0.0/0".
```
[vagrant@localhost ~]$  ip route show default
default via 10.0.2.2 dev enp0s3  proto static  metric 100
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15  metric 100
10.100.0.1
nexthop via 192.168.33.10  dev enp0s8 weight 1
nexthop via 192.168.33.20  dev enp0s9 weight 1
192.168.33.0/24 dev enp0s9  proto kernel  scope link  src 192.168.33.20  metric 100
192.168.33.0/24 dev enp0s8  proto kernel  scope link  src 192.168.33.10  metric 101
```
```
[vagrant@localhost ~]$ ip route …
```
> Fix ECMP route in routing_table

- lib/specinfra/command.rb
- lib/specinfra/command/amazon/v2.rb
- lib/specinfra/command/amazon/v2/service.rb
- spec/command/amazon2/service_spec.rb
There are probably some more differences between amazon linux v1 and v2, but this is the biggest one that can cause some downstream libraries (in my case, serverspec) to make incorrect calls to `service` when on Amazon Linux 2.
I mostly borrowed from how redhat v7 is differentiated, though I'm fine with whichever way we do it, as long as specinfra knows the right init system to use.
> support Amazon Linux 2 systemd init system

- lib/specinfra/command/base/cron.rb
This is a pull request to refine method `get_table()` to check all cron tables specified by Vixie Cron.
Thus, /etc/crontab, /etc/cron.d/* and /var/spool/cron/*.
Thanks.
> Refine method get_table

- lib/specinfra/command/base/cron.rb
(Sorry for many times.)
This is a pull request to refine method get_table() to check all cron tables specified by Vixie Cron.
Thanks a lot.
> Refine method get_table()

- lib/specinfra/host_inventory/virtualization.rb
KVM is already detected but sometimes we want to run systems with full
CPU emulation and have them spec'ed as well.
We check for empty dmidecode output since e.g. the arm machines may
return empty information.
> Detect qemu virtualization as well

- lib/specinfra/command/base/package.rb
Right now you usually have two Python versions installed and both exist in your path.
This PR allows you to check if a package is installed by pip into a Python 3 interpreter.
> Allow to check if a package is installed by pip3

- lib/specinfra/command/base/package.rb
Currently used regex for matching output for pip fails for following `pip list` output:
```
Package                          Version
-------------------------------- ---------
pip                              10.0.1
ply                              3.4
policycoreutils-default-encoding 0.1
pyasn1                           0.4.3
pycparser                        2.14
pycrypto                         2.6.1
```
When checking for `policycoreutils-default-encoding` grep, having both space at the end of regex and `-w` switch enabled expects to find 2 whitespaces after the package name (and it finds 1).
My fix removes space in the regex and lets `-w` switch to do its job.
> Fix check_is_installed_by_pip regex

- specinfra.gemspec
When I update vagrant-itamae plugin, a conflict occurs as follows.
```
% vagrant plugin update
Updating installed plugins...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:
conflicting dependencies net-ssh (= 4.2.0) and net-ssh (= 5.0.1)
Activated net-ssh-5.0.1
which does not match conflicting dependency (= 4.2.0)
Conflicting dependency chains:
net-ssh (= 5.0.1), 5.0.1 activated
versus:
net-ssh (= 4.2.0)
Gems matching net-ssh (= 4.2.0):
net-ssh-4.2.0
```
This is because specinfra requires net-ssh-4.2
but net-scp allows to use net-ssh-5.0.
I seems specinfa works with net-ssh-5.0.
All specs have passed. …
> allow to use net-ssh-5.0

- lib/specinfra/command/ubuntu/base/port.rb
- lib/specinfra/command/ubuntu/v18.rb
- lib/specinfra/command/ubuntu/v18/port.rb
I ran specs on Ubuntu 18 Server but failed be_listening as `netstat` is not installed by minimal install.
So I modified Ubuntu 18 to use the `ss` command instead of` netstat`.
> Use `ss` when Ubuntu v18

- lib/specinfra/command.rb
- lib/specinfra/command/amazon/v2/port.rb
- spec/command/amazon2/port_spec.rb
Amazon Linux 2 requires use of `ss` for port checking, just like RHEL 7.
> Use ss for Amazon Linux 2, instead of netstat

- specinfra.gemspec
Also added todo comments to come back and remove it at a later date and to pin to a min version of ruby at some point.
in version [version 0.2.0]([here](https://github.com/ruby/net-telnet/commit/4b5432a1d4f81e6c56bac6e72b0fe27bb8a6dfd8#diff-de0020d29d91153b0fe757ca69118a4e)) they dropped ruby version support for `< 2.3`. Pinning to `0.1.1` allows older setups to keep working and then can then be removed at the time in which the version of ruby this gem supports is declared in a major release.
Affects:
- https://github.com/sensu-plugins/sensu-plugins-logs/pull/34
- https://github.com/sensu-plugins/sensu-plugins-docker/pull/69
I plan on dropping those versions of ruby versions in the next major releases of those gems.
Signed-off-by: Ben Abrams <me@benabrams.it>
> pin `net-telnet` dependency to keep ruby support for < 2.3

- specinfra.gemspec
Since the install is really just an artifact buried deep on a user's system there's no need to ship the full test suite and documentation. This reduces the install size, especially for packaged products that use this gem.
> Reduce the number of files that ship in the gem artifact

- lib/specinfra/command.rb
- lib/specinfra/command/freebsd/base/service.rb
- lib/specinfra/command/freebsd/v6/service.rb
- lib/specinfra/command/freebsd/v7/service.rb
- lib/specinfra/command/freebsd/v8/service.rb
- lib/specinfra/command/freebsd/v9/service.rb
- spec/command/freebsd/service_spec.rb
I ran into an issue in serverspec checking that a service is not enabled on FreeBSD. If `openntpd` is enabled but `ntpd` is not, the following serverspec test fails when it should pass:
```
describe service('ntpd') do
it { should_not be_enabled }
end
```
This is because the regex `ntpd` matches `openntpd`, which is bad luck for me!
Initially I was attempting to improve the regex, but while reading the docs I found that [`service` supports an `enabled` command](https://www.freebsd.org/cgi/man.cgi?query=rc&apropos=0&sektion=8&manpath=FreeBSD+10.0-RELEASE&arch=default&format=html) which looks like exactly what is needed here:
```
enabled  Return 0 if	the service is enabled and 1 if	it is not.
This command does not print	anything.
```
That's what I've used here, and in my own testing this …
> Use built-in enabled check in FreeBSD's service command

- lib/specinfra/configuration.rb
When Ruby's warning is enabled, the following warning is printed:
```
/home/travis/build/itamae-kitchen/itamae/vendor/bundle/ruby/2.6.0/gems/specinfra-2.76.5/lib/specinfra/configuration.rb:54: warning: instance variable @path not initialized
```
It want to fix this to make it easier to read other warnings.
> Suppress uninitialized ivar warning

- lib/specinfra/command/module/ss.rb
- spec/command/amazon2/port_spec.rb
- spec/command/debian8/port_spec.rb
- spec/command/debian9/port_spec.rb
- spec/command/module/ss_spec.rb
- spec/command/redhat7/port_spec.rb
Hey,
I'm opening this empty PR because I'm not quite sure of how to handle this. While developing a change on a unrelated repository (https://github.com/voxpupuli/puppet-rabbitmq/pull/758) which uses specinfra I came across a bug.
The output off ss changed starting with (at least) version 4.14.0. Most certainly due to [this](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=1267c0b924de0297510efd48f8f849af774be369) change.
In "real life" this look as following:
Ubuntu 16.04 using iproute2/ss in version 4.3.0:
```
root@ubuntu1604-64-1:/# ss -tnl4 | grep 15672
LISTEN     0      128          *:15672                    *:*
root@ubuntu1604-64-1:/# which ss
/bin/ss
root@ubuntu1604-64-1:/# dpkg -S /bin/ss
iproute2: /bin/ss
root@ubuntu1604-64-1:/# dpkg -l | grep iproute2
ii …
```
> Output of ss changed in version 4.14; breaks Specinfra::Command::Module::Ss

- lib/specinfra/command/solaris/base/cron.rb
'%' needs to be manually escaped in the cron entry definition prior to grepping for the string in crontab -l output
> Add '%' to characters manually escaped in solaris cron check

- lib/specinfra/command.rb
- lib/specinfra/command/sles/v11.rb
- lib/specinfra/command/sles/v11/user.rb
- lib/specinfra/command/solaris/v11.rb
- lib/specinfra/command/solaris/v11/user.rb
- spec/command/sles11/user_spec.rb
- spec/command/solaris11/user_spec.rb
The output of chage on SLES 11 is different to other versions of SLES.
Additionally, Solaris 11 is not installed with chage so I have used
passwd to return the needed information.
> Support user_max/min_days on SLES 11 + Solaris 11

- lib/specinfra/backend/base.rb
Specinfra displays a warning on each command execution via SSH if `-w`
option is specified.
```
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/specinfra-2.77.1/lib/specinfra/backend/ssh.rb:24: warning: instance variable @example not initialized
```
This change will suppress the warnings.
> Suppress Ruby warning

- lib/specinfra/command/base/package.rb
I want to use pip2 command with serverspec.
Specinfra has `check_is_installed_by_pip()` and `check_is_installed_by_pip3()`, but not `check_is_installed_by_pip2()`.
So I implemented `check_is_installed_by_pip2()`.
Please consider my proposal.
> Implemented check_is_installed_by_pip2

- lib/specinfra/host_inventory/facter.rb
I'm still new to serverspec. On Windows hosts using the cmd backend I've had difficulty using the facter property of host_inventory. In debugging it seems that the .zero? method doesn't exist on the exit_status. Looking through specinfra for other compares for exit_status, it seems everything else is numeric. Changing this to a numeric compare fixed my issue locally.
> Change exit status to a numeric comapre.

- lib/specinfra/backend/cmd.rb
In the calling method run_command, it's possible @example is nil and is even checked for later in the method. A nil check is needed in the powershell method to handle cases where something like host_inventory is used outside of an example.
> Handle nil @example in cmd backend.

- lib/specinfra/command/base/group.rb
- lib/specinfra/command/base/user.rb
- spec/command/base/group_spec.rb
- spec/command/base/user_spec.rb
After adding with system_[user|group], I want to check whether it is a system account correctly.
```
The default value for SYS_UID_MIN (resp.  SYS_UID_MAX) is 101 (resp.  UID_MIN-1).
```
```
The default value for SYS_GID_MIN (resp.  SYS_GID_MAX) is 101 (resp.  GID_MIN-1).
```
See also: [login\.defs\(5\)](http://man7.org/linux/man-pages/man5/login.defs.5.html)
> Implemented check_belongs_to_system_account

- lib/specinfra/command/redhat/base/host.rb
- lib/specinfra/command/redhat/base/port.rb
- lib/specinfra/command/redhat/base/service.rb
When running a command test on a RHEL8 host I noticed that it was still relying on chkconfig.
> Wire in RHEL7 Service/Port/Host tests

- lib/specinfra/configuration.rb
- spec/backend/exec/build_command_spec.rb
Specinfra has two problems with Ruby 2.7-dev.
This pull request will fix the problems.
First, Specinfra::Configuration raises an error with Ruby 2.7.
I found the following backtrace with Itamae.
```
FrozenError: can't modify frozen String: "error_on_missing_backend_type="
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/specinfra-2.78.0/lib/specinfra/configuration.rb:47:in `gsub!'
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/specinfra-2.78.0/lib/specinfra/configuration.rb:47:in `method_missing'
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/itamae-1.10.4/lib/itamae/backend.rb:6:in `<top (required)>'
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/2.7.0/gems/itamae-1.10.4/lib/itamae.rb:10:in `require' …
```
> Fix issues for Ruby 2.7-dev

- lib/specinfra/command/ubuntu/v18/port.rb
Comparing it with other classes, I think `lib/specinfra/command/ubuntu/v18/port.rb` should have `Specinfra::Command::Ubuntu::V18::Port` like its path, not including `::Base` inside it.
> Fix a constant name inconsistent with its path

- lib/specinfra/backend/powershell/command.rb
`instance_eval &block` seems to always print the following warning:
```
.../lib/specinfra/backend/powershell/command.rb:9: warning: `&' interpreted as argument prefix
```
I'd like to remove the warning by this PR.
> Fix warning: `&' interpreted as argument prefix

- lib/specinfra/ec2_metadata.rb
backport of https://github.com/itamae-kitchen/mruby-specinfra/commit/d802a755cfa94675c6df80547ca553abb323ec7f
> Allow Symbol in EC2 metadata inventory

- lib/specinfra/command/openbsd/base/package.rb
`package` resource of mitamae required this to work on OpenBSD.
> Support package get_version on OpenBSD

- lib/specinfra/helper/detect_os/suse.rb
I'm trying to use mitamae on this kind of openSUSE environment:
```
ec2-user@ip-172-31-3-159:~> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.1"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```
I need this patch to run mitamae on the server.
> Relax openSUSE detection

- lib/specinfra/command.rb
- lib/specinfra/command/alpine/base/service.rb
- lib/specinfra/command/gentoo/base/service.rb
- lib/specinfra/command/module/openrc.rb
- lib/specinfra/command/module/service/openrc.rb
mitamae's `service` resource didn't work on a Gentoo machine because many OpenRC commands are missing in `Specinfra::Command::Gentoo::Base::Service`.
To make sure OpenRC commands are used on Gentoo, I shared OpenRC service commands between Alpine and Gentoo, and added reload implementation to it.
> Support all OpenRC commands in Gentoo

- lib/specinfra/command/darwin/base/host.rb
- spec/command/darwin/host_spec.rb
The netcat implementation on Darwin has the -G option setting the tcp
connection timeout, whereas the -w option sets the STDIN idle timeout.
> fix: use nc -G option for timeout

- lib/specinfra/command/base/user.rb
`id` outputs the first uid that matches when presented with potentially multiple users with the same uid. This means that if 2 users with the same uid are present all of the calls to `id` may return the incorrect user. `getent` has this same property when looking up users by `uid` but this doesn't happen when looking them up using their name.
> Fix user.rb for non-unique uids

- lib/specinfra/command/base/user.rb
check_belongs_to_primary_group does not work correctly.
This reverts commit dcfc3343399cba5c7ea3916f4b418a35389403fe, reversing
changes made to 216c80f350056fbfcec4887af8c18a2735f6bb7b.
> Revert "Merge pull request #714 from lswith/patch-1"

- lib/specinfra/backend/powershell/support/is_port_listening.ps1
This change avoids matching against a port that is in TIME_WAIT or other non-listening states
Also, allow matching on ipv6 local
> Ensure the matched port is listening

- lib/specinfra/backend/ssh.rb
net-ssh 6.0 seems not to support this options like this error:
```
net-ssh-6.0.2/lib/net/ssh.rb:221:in `start': invalid option(s):
strict_host_key_checking (ArgumentError)
```
> Remove strict_host_key_checking option when net-ssh does not support it

- lib/specinfra/command/darwin/base/file.rb
The default file size command, `stat -c`, does not work on macOS:
```
$ stat -c /Users/Shared
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```
This PR adds a `get_size()` method for darwin that uses `stat -f %z` (same command as free/openbsd).
**Test:**
```ruby
describe file("/Users/Shared") do
its(:size) { should > 10 }
end
```
**Before:**
```ruby
$ rspec
File "/Users/Shared"
size
is expected to > 10 (FAILED - 1)
Failures:
1) File "/Users/Shared" size is expected to > 10
Failure/Error: its(:size) { should > 10 }
expected: > 10
got:   0
/bin/sh -c stat\ -c\ \%s\ /Users/Shared
Finished in 0.19662 seconds (files took 0.90007 seconds to load)
1 example, 1 failure
Failed examples:
rspec ./spec/localhost/sample_spec.rb:4 # File "/Users/Shared" size is …
```
> Add get_size(file) for darwin

- lib/specinfra/host_inventory/virtualization.rb
A VMware guest booted with UEFI will report 'VMWare7,1' in the DMI product
name but parse_system_product_name() only looks for 'VMware Virtual Platform'
which is what it reports when booted with legacy BIOS.
> Detect UEFI VMware guests

- lib/specinfra/backend/powershell/support/find_installed_gem.ps1
- lib/specinfra/command/windows/base/package.rb
Example:
describe package("#{spec.name}") do
it { should be_installed.by("gem").with_version(spec.version) }
end
This commit fixes the following error:
check_is_installed_by_gem is not implemented in Specinfra::Command::Windows::Base::Package
> Windows: support check_is_installed_by_gem

- lib/specinfra/backend/powershell/support/find_installed_gem.ps1
In the previous version, foobar (x.y.z x64-mingw32)
is not detected correctly.
> Windows: fix wrong gem version detection

- lib/specinfra/command/module/ss.rb
- spec/command/module/ss_spec.rb
- make sure tests have IPv6 format instead IPv4
- fix local_address format when addresses are IPv6 (i.e. contain
at least one colon): ss reports those addresses between brackets
> ss: fix local_address format for IPv6.

- lib/specinfra/command/darwin/base/service.rb
[Homebrew](https://github.com/Homebrew/homebrew-services) now supports services.
I still haven't add any tests because I wasn't exactly sure if I was supposed to create a `service_spec.rb` for it or if `darwin` should be a submodule like `Specinfra::Command::Module::Service::Systemd`
I know Homebrew is now supported on other systems so I guess maybe a module?  But i'm less clear how to do that correctly.
> Add: Services check for Homebrew

- lib/specinfra/backend/powershell/support/find_installed_gem.ps1
In the previous version, installed multiple version is not
handled correctly, so only last version is detected correctly.
Before:
If rake (13.0.3, 13.0.1) then, FindInstalledGem("rake", "13.0.3")
returns False because ["13.0.3,", "13.0.1"].Contains("13.0.3") is
checked.
After:
If rake (13.0.3, 13.0.1) then, FindInstalledGem("rake", "13.0.3")
returns True because ["13.0.3", "13.0.1"].Contains("13.0.3") is
checked.
> windows: fix version detection when multiple gem is installed

- lib/specinfra/command/debian/base/port.rb
- lib/specinfra/command/debian/base/service.rb
- spec/command/debiantesting/port_spec.rb
- spec/command/debiantesting/service_spec.rb
- spec/command/debianunstable/port_spec.rb
- spec/command/debianunstable/service_spec.rb
This allows proper service and port management of hosts using unreleased
versions of Debian, which were being identified as pre-v8 and thus not
using systemd/ss properly.
> debian: add support for Debian testing and unstable

- appveyor.yml
I found a solution to the error about the certificate in the official documentation.
https://www.appveyor.com/docs/lang/ruby/#openssl-verification
`Use set SSL_CERT_FILE=C:/ruby24-x64/ssl/cert.pem`
> use localcert for older rubies on appvayor test

- lib/specinfra/command/darwin/base/package.rb
resolves NoMethodError: NoMethodError: undefined method 'basename' for
Specinfra::Command::Darwin::Base::File in darwin environment.
Since upgrading mitamae >= v1.12.2 (includes upgrading mruby from v2.1.2 to v3.0.0), I've been getting the following error with package resource in darwin environment:
```bash
$ ./mitamae-aarch64-darwin version
mitamae v1.12.3
$ cat recipe.rb
package 'git'
$ ./mitamae-aarch64-darwin local recipe.rb --log-level=debug
INFO : Starting mitamae...
DEBUG : Loading recipe: recipe.rb
INFO : Recipe: /Users/rrreeeyyy/sandbox/mitamae/recipe.rb
DEBUG :   package[git]
DEBUG :     package[git] action: install
DEBUG :       (in set_desired_attributes)
DEBUG :       (in set_current_attributes)
undefined method 'basename' (NoMethodError)
```
This error is due to the File …
> Resolve namespace properly for File

- lib/specinfra/command/darwin/base/inventory.rb
- spec/host_inventory/darwin/kernel_spec.rb
Since `get_kernel` inventory command is unavailable on Darwin, the value of `host_inventory["kernel"]["machine"]` is unavailable though it is provided from `os_info`:
```
$ ruby -Ilib -rspecinfra -e "p Specinfra::HostInventory.instance['kernel']['machine']"
No backend type is specified. Fall back to :exec type.
/Users/mrkn/src/github.com/mizzy/specinfra/lib/specinfra/command_factory.rb:20:in `get': get_kernel is not implemented in Specinfra::Command::Darwin::Base::Inventory (NotImplementedError)
from /Users/mrkn/src/github.com/mizzy/specinfra/lib/specinfra/host_inventory/kernel.rb:8:in `get'
from /Users/mrkn/src/github.com/mizzy/specinfra/lib/specinfra/host_inventory.rb:42:in `[]'
from -e:1:in `<main>'
```
Ignoring `NotImplementedError` occurred in `CommandFactory#get` makes it always …
> Make host_inventory["kernel"]["machine"] always available

- lib/specinfra/command/linux/base/inventory.rb
- spec/command/linux/inventory_spec.rb
get_block_device command use brace expansion but sh doesn't support it.
I think the commands should be execeted via bash.
```rb
irb(main):001:0> require 'specinfra'
=> true
irb(main):002:0> backend = Specinfra::Backend::Exec.new
=> #<Specinfra::Backend::Exec:0x00005598189ffbb8 @config={}, @example=nil>
irb(main):003:0> host_inventory = Specinfra::HostInventory.new(backend)
=> #<Specinfra::HostInventory:0x00005598189e99d0 @backend=#<Specinfra::Backend::Exec:0x00005598189ffbb8 @config={}, @example=nil>, @inventory={}>
irb(main):004:0> block_device = Specinfra::HostInventory::BlockDevice.new(host_inventory)
=> #<Specinfra::HostInventory::BlockDevice:0x00005598189aac58 @host_inventory=#<Specinfra::HostInventory:0x00005598189e99d0 @backend=#<Specinfra::Backend::Exec:0x00005598189ffbb8 …
```
> fix get_block_device

- lib/specinfra/backend/cmd.rb
It's removed as of Ruby 3.2
FYI: https://github.com/fluent/fluent-package-builder/pull/425#issuecomment-1406190223
> Replace obsolete File.exists? with File.exist?

- lib/specinfra/command.rb
- lib/specinfra/command/neon.rb
- lib/specinfra/command/neon/base.rb
Trying out Itamae for local laptop management and found that Neon support was missing in specinfra.  This adds it in. :)
Test itamae recipe:
```
http_request 'testing' do
url "https://raw.githubusercontent.com/mizzy/specinfra/master/examples/multiple_backends.rb"
action :get
mode '0644'
end
```
Results:
```
itamae local test.rb
INFO : Starting Itamae... 
INFO : Recipe: /home/[snipped]/test.rb
INFO :   http_request[testing] modified will change from 'false' to 'true'
INFO :   http_request[testing] mode will be '0644'
INFO :   diff:
INFO :   --- testing (BEFORE)
INFO :   +++ testing (AFTER)
INFO :   @@ -0,0 +1,46 @@
INFO :   +require 'specinfra'
INFO :   +require 'pp'
```
> add KDE Neon support

- lib/specinfra/command.rb
- lib/specinfra/command/vyos.rb
- lib/specinfra/command/vyos/base.rb
This PR adds support for [VyOS](https://vyos.io/).
Test:
```rb
http_request 'testing' do
url "https://raw.githubusercontent.com/mizzy/specinfra/master/examples/multiple_backends.rb"
action :get
mode '0644'
end
```
Before:
```
$ itamae ssh -h <host> testing.rb
INFO : Starting Itamae... 
INFO : Recipe: /Users/**/testing.rb
/**/gems/specinfra-2.85.1/lib/specinfra/command_factory.rb:31:in `create_command_class': uninitialized constant Specinfra::Command::Vyos (NameError)
os_class     = family.nil? ? base_class : common_class.const_get(family.capitalize)
^^^^^^^^^^
```
After:
```
$ itamae ssh -h <host> testing.rb
INFO : Starting Itamae... 
INFO : Recipe: /Users/**/testing.rb
INFO :   http_request[testing] modified will change from 'false' to 'true'
INFO :   http_request[testing] mode will be …
```
> Add VyOS Support

- lib/specinfra/command.rb
- lib/specinfra/command/amazon/v2023.rb
All relevant behavior should be identical to Amazon Linux 2022. I'm not sure if any other files are needed, but this change works well in my testing.
> Add support for Amazon Linux 2023

- lib/specinfra/backend/exec.rb
- lib/specinfra/version.rb
- specinfra.gemspec
Hello,
This will change the dependencies according to the Ruby version:
* `sfl`: Add the dependency only if Ruby is older than 1.9.0.
* `net-telnet`: Use the version newer than 0.1.1 if Ruby version is 2.3.0 or higher.
Thank you,
> Use newer version of dependency or omit one for newer Ruby version

- .github/workflows/test.yaml
- README.md
- spec/backend/exec/build_command_spec.rb
- specinfra.gemspec
This is a continuation of #746.
The summary of changes are bellow:
* Remove gem version conditionals in the gemspec file, which is evaluated in release phase, so one cannot use conditionals in the file.  This is a regression of #746.
* Use an unfrozen string value in the test code.  This passes the test workflow for the Ruby v.1.9.3.
* Remove Rake version constraint from the gemspec file.  Older Rake has an issue with the latest Ruby version.
* Use Ubuntu 20.04 for Ruby 2.2.10.  Bundler cannot be installed with Ruby 2.2.10 on the latest Ubuntu.
Please refer also to the pointers in commit messages.
Best,
> Remove version constraints in gemspec and some CI workflow fixes

- Rakefile
- lib/specinfra/backend/lxd.rb
- spec/backend/lxd/build_command_spec.rb
made a mistake in the #750 PR with methods being on the object not the instance 👎 
using the docker backend as a template was a mistake as lxd is more like the ssh backend.
reworked the lxd backend, very simple and straightforward now.
added unit tests to ensure everything works as expected.
> fix, simplify and add tests for lxd backend

- lib/specinfra/host_inventory/virtualization.rb
- spec/host_inventory/linux/virtualization_spec.rb
In detecting virtualization, if system-product-name from DMI is unknown to Specinfra, fallback to `systemd-detect-virt`, which has better heuristics. It currently returns `{system: nil}` in such a case.
> host_inventory/linux/virtualization: Fallback to systemd-detect-virt

- specinfra.gemspec
Fixed the following warning when running `serverspec` on Ruby 3.3
```bash
$ ruby --version
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]
$ bundle exec rspec
/app/vendor/bundle/ruby/3.3.0/gems/specinfra-2.90.0/lib/specinfra/backend/powershell/script_helper.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of specinfra-2.90.0 to add base64 into its gemspec.
```
See "Standard library updates" section in https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
> Add base64 as runtime dependency

- lib/specinfra/backend/exec.rb
- spec/backend/exec/env_spec.rb
In bundler >= 2.4 and rubygems >= 3.4, "BUNDLER_SETUP" environment variable affects the bundle command execution.
So I have clear it.
> Clear BUNDLER_SETUP env in exec

- lib/specinfra/helper/detect_os/debian.rb
- spec/helper/detect_os/debian_spec.rb
Debian is nearing its next release so it would be nice if `os[:release]` is not `nil` on Debian Testing/Trixie. This is a rework of #741, for a rationale of this implementation see https://github.com/mizzy/specinfra/pull/741#issuecomment-1836279113
> Detect Debian Testing and assign a impossibly high version number

- lib/specinfra/helper/detect_os/debian.rb
- lib/specinfra/host_inventory.rb
- lib/specinfra/host_inventory/platform_codename.rb
- spec/backend/exec/build_command_spec.rb
- spec/helper/detect_os/debian_spec.rb
In Debian and Ubuntu, codenames are used in various places, such as APT repository settings.
If the codenames can be obtained from the host inventory, users will no longer need to check the /etc/os-release file individually.
> feat: Add `platform_codename` host inventory

- lib/specinfra/ext/class.rb
- lib/specinfra/version.rb
When invoke any command like 'rake db:create' which the project depends on ruby >= 3.1 and specinfra, it causes
> rake aborted!
> SystemStackError: stack level too deep (SystemStackError)
> ...
because spcinfra redefines Class#subclasses while ruby (>= 3.1) already have.
This PR fixes by define Class#subclasses only when ruby does not such a  method.
`git diff -w` would be better to see the modification of this PR.
> fix 'stack level too deep' caused by local re-definition of Class#subclasses

- .github/workflows/test.yaml
Local runs are broken out of the box.
CI is also very very out of date. 3.2 is the latest but next to EOL.
Please enable issues. This is hostile to contributions.
```
/Users/ryan/Work/p4/zss/usr/root/ansible/mitamae/specinfra/spec/host_inventory/base/user_spec.rb:38: warning: key "root" is duplicated and overwritten on line 57
..........FFFFFFFF...................................FFFFFFFFFF........................................................................................................................................................................................................................................................................................................................................................................................................................ …
```
> CI seems not to be running for the last year despite recent commits
