mizzy/specinfra

lib/specinfra/backend/docker.rb

With this fix, Docker backend uses `exec` to execute commands.
Before this fix, Specinfra runs up container every time when running a command.
So this fix shorten the time to execute commands.
Also with this fix, you can execute commands in arleady running containers by specifying a container name or ID like this.
```ruby
set :docker_container, 'lonely_payne'
```

Use exec with Docker backend and support executing commands in already running containers

---

lib/specinfra/backend/docker.rb

Added the ability to pass through the docker environment variables to the container when starting.
Fixed the path environment variable, they must be an array of KEY=val strings.

Docker Environment Variables.

---

lib/specinfra/command/base/user.rb
spec/command/base/user_spec.rb

This is from https://github.com/itamae-kitchen/itamae/blob/9224dac83abcaa1f9d4fb67bb9b36d6a62808fb4/lib/itamae/ext/specinfra.rb#L5-L8

Implement update_user_home_directory.

---

lib/specinfra/ec2_metadata.rb

Recue only LoadError in ec2_metadata

---

lib/specinfra/command.rb
lib/specinfra/command/coreos.rb
lib/specinfra/command/coreos/base.rb
lib/specinfra/command/coreos/base/service.rb
lib/specinfra/helper/detect_os.rb
lib/specinfra/helper/detect_os/coreos.rb

CoreOS Support

---

lib/specinfra/backend/cmd.rb
lib/specinfra/backend/winrm.rb

Ref: https://github.com/chef/chef/pull/3048

Do not call set in the case of not including Specinfra::Helper::Set

---

spec/command/module/zfs_spec.rb

add test for Specinfra::Command::Module::Zfs based of spec/command/module/systemd_spec.rb

add test for Specinfra::Command::Module::Zfs

---

lib/specinfra/backend/docker.rb

This PR is for Itamae's Docker backend.
- Pull a docker image if it is not found.
- Implement Backend::Docker#commit_container
- Always pass OpenStdin to docker run
docker-backend branch: https://github.com/itamae-kitchen/itamae/compare/docker-backend

Improve Docker backend

---

examples/multiple_backends.rb
lib/specinfra.rb
lib/specinfra/backend/base.rb
lib/specinfra/backend/cmd.rb
lib/specinfra/backend/docker.rb
lib/specinfra/backend/dockerfile.rb
lib/specinfra/backend/exec.rb
lib/specinfra/backend/lxc.rb
lib/specinfra/backend/powershell/script_helper.rb
lib/specinfra/backend/ssh.rb
lib/specinfra/backend/telnet.rb
lib/specinfra/backend/winrm.rb
lib/specinfra/command_factory.rb
lib/specinfra/helper/detect_os.rb
lib/specinfra/helper/detect_os/aix.rb
lib/specinfra/helper/detect_os/alpine.rb
lib/specinfra/helper/detect_os/arch.rb
lib/specinfra/helper/detect_os/coreos.rb
lib/specinfra/helper/detect_os/darwin.rb
lib/specinfra/helper/detect_os/debian.rb
lib/specinfra/helper/detect_os/esxi.rb
lib/specinfra/helper/detect_os/freebsd.rb
lib/specinfra/helper/detect_os/gentoo.rb
lib/specinfra/helper/detect_os/nixos.rb
lib/specinfra/helper/detect_os/openbsd.rb
lib/specinfra/helper/detect_os/plamo.rb
lib/specinfra/helper/detect_os/redhat.rb
lib/specinfra/helper/detect_os/solaris.rb
lib/specinfra/helper/detect_os/suse.rb

This PR make Specinfra be able to create multiple backends and this is for Itamae's multiple backends feature.
Here is example usage: https://github.com/ryotarai/specinfra/blob/multiple-backend/examples/multiple_backends.rb
I think these changes don't break current compatibility. If you find any incompatibility, please tell me that.

Support multiple backends.

---

lib/specinfra/backend/base.rb
lib/specinfra/backend/ssh.rb
lib/specinfra/ec2_metadata.rb
lib/specinfra/host_inventory.rb
lib/specinfra/host_inventory/base.rb
lib/specinfra/host_inventory/cpu.rb
lib/specinfra/host_inventory/domain.rb
lib/specinfra/host_inventory/ec2.rb
lib/specinfra/host_inventory/filesystem.rb
lib/specinfra/host_inventory/fqdn.rb
lib/specinfra/host_inventory/hostname.rb
lib/specinfra/host_inventory/memory.rb
lib/specinfra/host_inventory/platform.rb
lib/specinfra/host_inventory/platform_version.rb
spec/host_inventory/cpu_spec.rb

A backend should have a host inventory.
specinfra-ec2_metadata-tags will be broken by this change. I'll send a PR to it.

Host inventory multi backend

---

lib/specinfra.rb
lib/specinfra/helper.rb

I forgot to include this change into https://github.com/serverspec/specinfra/pull/358
五月雨式でスミマセン…

Do not include helper modules from specinfra/core.

---

lib/specinfra.rb

It stopped working with chef and its OSS so I fixed it? 
Ref: https://twitter.com/gosukenator/status/589003773894217728

I like chef? Please don't make my life harder?

---

lib/specinfra/command/base/user.rb
spec/command/base/user_spec.rb

Adding support for "shell" option.(for itamae

Add "shell" option to user

---

lib/specinfra/command/base/user.rb
spec/command/base/user_spec.rb

Methods to be used in serverspec. I haven't bumped the version as I can see from the git history this is not normally bumped by the pull requests. The associated pull request with serverspec does rely on a new release of specinfra though.

Add methods to check the minimum and maximum password change days

---

lib/specinfra/command/base/file.rb
spec/command/base/file_spec.rb

link_toでforceオプションを使えるようにしました。

Support force option on link_to

---

lib/specinfra/command/windows/base/registry_key.rb

- Property needed to be passed along and is not attribute of class

(fix) Address issue with registry_key

---

lib/specinfra/command.rb
lib/specinfra/command/amazon.rb
lib/specinfra/command/amazon/base.rb
lib/specinfra/helper/detect_os/redhat.rb
spec/command/amazon/interface_spec.rb
spec/command/amazon/package_spec.rb
spec/command/amazon/service_spec.rb

Another implementation of #406 .

Support Amazon Linux separated with Red Hat

---

lib/specinfra/host_inventory/cpu.rb
lib/specinfra/host_inventory/filesystem.rb
lib/specinfra/host_inventory/memory.rb
spec/host_inventory/filesystem_spec.rb
spec/host_inventory/memory_spec.rb

... for filesystem, cpu and memory. This will be in preparation for platforms where it is hard to exactly replicate the same behaviour Linux exhibits. Also added a unit test for host_inventory's memory and modified the filesystem one to work with the new changes.

Checking the exit_status of the executed command in host_inventory

---

lib/specinfra/backend/exec.rb
specinfra.gemspec

Reverts serverspec/specinfra#434

Revert "Change how to run command with exec backend"

---

lib/specinfra/backend/exec.rb
specinfra.gemspec

Sometimes, `spawn_command` ends before the thread is done, so wait it: https://github.com/serverspec/specinfra/commit/715bdd026b5e5e62ef57fa101924d64c9f9fbd17

Change how to run command with exec backend (retry)

---

lib/specinfra/backend/exec.rb

Fix for a problem mentioned in the comments for https://github.com/serverspec/specinfra/pull/442
This solution does not depend on a pipe read size and also works a bit faster then a default one.
NB: block behavior has changed in terms of output buffers updating. They are updated at the end of a command run only. However, this should not be a problem as far as I see the rest of the #spawn_command code. 
P.S. I didn't check if other backends may have similar problem.
**Test code:**
```ruby
require 'serverspec'
set :backend, :exec
shared_examples "IO checks" do
let (:generator) { "seq 1 #{max}" }
let (:expected) { (1..max).map { |x| x.to_s }.join("\n") << "\n" }
it "stdout only" do
out = command(generator).stdout
expect(out).to eq expected
end
it "stderr only" do
out = command("#{generator} …
```

Do not depend on pipe buffer size

---

lib/specinfra/command.rb
lib/specinfra/command/alpine/base/service.rb

This allows you to test if a service is enabled and to test if a service is running.

Add service resource type for Alpine Linux

---

lib/specinfra/command/base/cron.rb

Add get_cron_table command

---

lib/specinfra/command/darwin/base/host.rb
spec/command/darwin/host_spec.rb

- is_resolvable: Using dig instead of nslookup; simplyfies query and adds ipv6
- get_*address: Using dscacheutil as getent is not available.

host: Adding darwin :ipv4_address and :ipv6_address

---

lib/specinfra/command/freebsd/base/interface.rb
spec/command/freebsd/interface_spec.rb

Verbatim copy of the darwin code to emulate the same behavior as on linux, openbsd and darwin.

interface: Changing freebsd code to align with darwin and openbsd

---

appveyor.yml

Same as https://github.com/mizzy/serverspec/pull/539 .

set dependencies to purge cache when updated appveyor.yml.

---

lib/specinfra/command/openbsd/base/mail_alias.rb
spec/command/openbsd/mail_alias_spec.rb

This is a follow up to pull request #490 to ensure openbsd does the same as base. If you reject #490 don't take this one either.

mail_alias: Adjusting openbsd to behave the same as base

---

lib/specinfra/command/redhat/base/yumrepo.rb

Ref #499
I've also added specs for yumrepo to the integration tests.
https://github.com/serverspec/serverspec-integration-test/commit/37b28e7b5b2edb06731bae748cbc55e1bfdbe5a5

Fix regexp of yum repolist to match /

---

lib/specinfra/command/darwin/base/package.rb

`Specinfra::Command::Darwin::Base::Package` has not uninstall package command.
Can you please feedback this PR :)

Add function to uninstall package for darwin

---

lib/specinfra/command/freebsd/base/user.rb

I got an advice of better password handling.
chpass(1) has '-p' option which specifiies encrypted password string.
I fixed to use this command.

Fix command freebsd

---

lib/specinfra/backend/powershell/script_helper.rb

works for both single and multiple commands this way

mutliple commands needs to be executes as $(commands) 

---

lib/specinfra/backend/cmd.rb

In Cygwin ruby, system() shells to `bash` instead of `cmd.exe`.  Detect this and fix the path to `powershell.exe` be valid within Cygwin.  The `encodedCommand` itself is base-64 encoded and handled by powershell, so it doesn't need to be changed.

Add support for Cygwin

---

lib/specinfra/command/alpine/base/service.rb
spec/command/alpine/service_spec.rb

Add enable, disable, start, stop and restart commands to Alpine Linux.
cf. Alpine Linux Init System
https://wiki.alpinelinux.org/wiki/Alpine_Linux_Init_System

Support the init system for Alpine Linux

---

lib/specinfra/command/base/inventory.rb
lib/specinfra/host_inventory.rb
lib/specinfra/host_inventory/user.rb
spec/host_inventory/base/user_spec.rb

Add `user` information to host_inventory

Support host_inventory['user']

---

lib/specinfra/command/base/inventory.rb
lib/specinfra/host_inventory.rb
lib/specinfra/host_inventory/group.rb
spec/host_inventory/base/group_spec.rb

Add `group` information to host_inventory

Support host_inventory['group']

---

.gitignore
README.md
Rakefile

Added default task to run tests. Added comment in readme that documents it.

Added default task to run rake spec:all

---

lib/specinfra/command/aix/base/file.rb

implements check_has_mode for aix

implements check_has_mode for aix

---

lib/specinfra/command.rb

Fix s/inhefit/inherit/

---

lib/specinfra/command/gentoo/base/package.rb

Implement some methods for `Gentoo::Base::Package` follows:
* `get_version`
* `install`
* `remove`

Implement some methods for Gentoo::Base::Package

---

lib/specinfra/command.rb
lib/specinfra/command/elementary.rb
lib/specinfra/command/elementary/base.rb

Support elementary OS which is a Linux distribution based on Ubuntu.

Support elementary OS

---

lib/specinfra/command.rb
lib/specinfra/command/freebsd/base/interface.rb
lib/specinfra/command/freebsd/v11.rb
lib/specinfra/command/freebsd/v11/interface.rb
spec/command/freebsd/interface_spec.rb

- add support of interface speed
- add support of interface mtu
- fix to handle ipv4 cidr
- fix to handle ipv6 cidr

Fix support of FreeBSD interface

---

lib/specinfra/command.rb
lib/specinfra/command/debian/base/port.rb
lib/specinfra/command/debian/base/service.rb
spec/command/debian9/port_spec.rb
spec/command/debian9/service_spec.rb

Support Debian 9

---

lib/specinfra/host_inventory.rb
lib/specinfra/host_inventory/facter.rb
lib/specinfra/host_inventory/ohai.rb

Adds Facter and Ohai as optional additional sources of information for host_inventory.

Facter/Ohai support for host_inventory

---

lib/specinfra/command/windows/base/firewall.rb

We wanted to check out windows firewall rules... there is a very basic set of checks in here for now.  I also have the serverspec code that goes with these checks.

Add a very basic set of windows firewall checks

---

appveyor.yml

Ref: https://github.com/appveyor/ci/issues/1944

Install bundler with `--force` on appveyor.

---

.travis.yml
lib/specinfra/helper/configuration.rb

Ref https://github.com/mizzy/serverspec/pull/603

Work around for avoid unintentional replacing of lxc configuration

---

appveyor.yml

- use `--no-document` for gem install
- add newer rubies

fix appveyor test

---

lib/specinfra/command/base/group.rb
spec/command/base/group_spec.rb

`-r, --system` option of [groupadd(8)](https://linux.die.net/man/8/groupadd)

Add system_group option

---

lib/specinfra/command/redhat/base/host.rb
lib/specinfra/command/redhat/base/port.rb
lib/specinfra/command/redhat/base/service.rb

#695 breaks compatibility with Amazon Linux. So I fixed it.

Fix for compatibility with Amazon Linux

---

.travis.yml

Just added and already passed ✅

add 2.6 to travis

---

lib/specinfra/command/esxi/base/package.rb
spec/command/esxi/package_spec.rb

Add code to check_is_installed for Esxi::Base::Package
- Add grep option to package check
- Add version check
I'm tested at VMware ESXi 6.7

Add version check to check_is_installed for Esxi::Base::Package

---

lib/specinfra/command.rb
lib/specinfra/command/darwin/base/group.rb
lib/specinfra/command/darwin/base/user.rb
spec/command/darwin/group_spec.rb
spec/command/darwin/user_spec.rb

Thank you for your great library.
Some OS commands for using user and group commands are not in darwin. Therefore, I have replaced them.

Add support user/group commands for darwin

---

lib/specinfra/backend/docker.rb

I have the following warning message:
```
warning: finalizer references object to be finalized
```
from:
```
vendor/bundle/ruby/3.0.0/gems/specinfra-2.83.3/lib/specinfra/backend/docker.rb:20
```
using ``specinfra`` ``2.83.3`` with ruby ``3.0.0``.
I have read the following blog post [The Trouble with Ruby Finalizers](https://www.mikeperham.com/2010/02/24/the-trouble-with-ruby-finalizers/).
As a result, I can suggest this pull request.

Fix warning related to finalizer in docker backend

---

lib/specinfra/command.rb
lib/specinfra/command/amazon/v2022.rb
lib/specinfra/command/amazon/v2022/package.rb
lib/specinfra/command/amazon/v2022/port.rb
lib/specinfra/command/amazon/v2022/service.rb
lib/specinfra/command/amazon/v2022/yumrepo.rb
spec/command/amazon2022/package_spec.rb
spec/command/amazon2022/port_spec.rb
spec/command/amazon2022/service_spec.rb
spec/command/amazon2022/yumrepo_spec.rb

ref. https://aws.amazon.com/linux/amazon-linux-2022/

Support Amazon Linux 2022

---

lib/specinfra/ec2_metadata.rb

modify to use IMDSv2 for retrieving EC2 metadata. Because only IMDSv2 is enabled by default and IMDSv1 will no longer be supported on new instance types in the future.

use IMDSv2 to retrieve ec2 metadata
